# CNN para clasificar dígitos
*Visión por computadora · IA aplicada & Agentes*

In [1]:
#@title 📌 Portada
from IPython.display import HTML, display
display(HTML(r'''<style>
  @import url('https://fonts.googleapis.com/css2?family=Archivo+Black&family=Archivo:wght@400;500;600;700&family=Archivo+Expanded:wght@600;700;800&display=swap');

  /* ===================================================================
     SISTEMA EDITORIAL CINEMATOGRÁFICO OSCURO
     Paleta fría documental · tipografía display extruida · vidrio esmerilado
     =================================================================== */

  /* ---------- contenedor base ---------- */
  .edu{max-width:1140px;margin:24px auto;font-family:'Archivo',system-ui,sans-serif;
       color:#dde7f2;line-height:1.66;font-size:15px;}
  .edu *{box-sizing:border-box;}

  /* ---------- hoja: panel de vidrio oscuro ---------- */
  .edu-sheet{position:relative;overflow:hidden;border-radius:22px;padding:36px 44px 40px;
     color:#e6eef8;background:linear-gradient(168deg,rgba(17,30,47,.94),rgba(9,16,27,.96));
     border:1px solid rgba(140,180,224,.14);
     box-shadow:0 30px 70px rgba(3,8,18,.55),inset 0 1px 0 rgba(255,255,255,.05);}
  .edu-sheet::before{content:"";position:absolute;top:0;left:0;right:0;height:4px;
     background:linear-gradient(90deg,#1d6fb0,#43c4b0 35%,#7fd4ff 55%,#43c4b0 75%,#1d6fb0);
     background-size:220% 100%;animation:eduBarFlow 7s linear infinite;}
  .edu-sheet::after{content:"";position:absolute;inset:0;pointer-events:none;z-index:0;opacity:.5;
     background:radial-gradient(110% 60% at 88% -10%,rgba(127,212,255,.10),transparent 60%);}
  .edu-sheet>*{position:relative;z-index:1;}

  /* ---------- eyebrow / etiqueta ---------- */
  .edu-eyebrow{display:inline-block;font-family:'Archivo Expanded','Archivo',sans-serif;
     font-size:10.5px;font-weight:700;letter-spacing:3px;text-transform:uppercase;color:#7fd4ff;
     background:rgba(127,212,255,.08);border:1px solid rgba(127,212,255,.30);
     padding:6px 16px;border-radius:999px;margin-bottom:18px;animation:eduPulse 3.4s ease-in-out infinite;}

  /* ---------- títulos ---------- */
  .edu h2{font-family:'Archivo Expanded','Archivo',sans-serif;color:#f1f7ff;font-size:23px;
     font-weight:800;letter-spacing:.3px;text-transform:uppercase;margin:34px 0 14px;
     padding:6px 0 10px 18px;border-left:4px solid #43c4b0;
     background:linear-gradient(90deg,rgba(67,196,176,.12),transparent 60%);}
  .edu h2:first-child{margin-top:0;}
  .edu h2.alt{border-left-color:#ff8f6b;background:linear-gradient(90deg,rgba(255,143,107,.13),transparent 60%);}
  .edu h3{color:#7fd4ff;font-size:12px;font-weight:700;letter-spacing:1.4px;
     text-transform:uppercase;margin:22px 0 6px;font-family:'Archivo Expanded','Archivo',sans-serif;}
  .edu p{margin:9px 0;color:#cdd9e7;}
  .edu b,.edu strong{color:#ffffff;font-weight:700;}
  .edu i,.edu em{color:#bfe6ff;}
  .edu code{background:rgba(127,212,255,.12);border:1px solid rgba(127,212,255,.26);border-radius:5px;
     padding:1px 7px;font-size:13px;color:#bfe6ff;font-family:ui-monospace,Menlo,monospace;}

  /* ---------- listas con viñeta propia ---------- */
  .edu ul{margin:6px 0;padding-left:2px;list-style:none;}
  .edu ul li{position:relative;padding-left:26px;margin:8px 0;color:#cdd9e7;}
  .edu ul li::before{content:"";position:absolute;left:4px;top:9px;width:8px;height:8px;border-radius:2px;
     background:linear-gradient(135deg,#7fd4ff,#43c4b0);transform:rotate(45deg);box-shadow:0 0 8px rgba(127,212,255,.5);}

  /* ---------- tablas ---------- */
  .edu-tbl{border-collapse:separate;border-spacing:0;width:100%;font-size:14px;margin:16px 0;
     border:1px solid rgba(140,180,224,.16);border-radius:14px;overflow:hidden;
     background:rgba(8,15,26,.45);box-shadow:0 10px 30px rgba(3,8,18,.4);}
  .edu-tbl th{background:linear-gradient(135deg,#103a5e,#1c6aa6);color:#eaf4ff;font-weight:700;
     padding:12px 15px;text-align:left;letter-spacing:.4px;border:none;
     font-family:'Archivo Expanded','Archivo',sans-serif;font-size:12px;text-transform:uppercase;}
  .edu-tbl td{padding:10px 15px;border:none;border-top:1px solid rgba(140,180,224,.10);color:#d4e0ee;}
  .edu-tbl tr:nth-child(even) td{background:rgba(255,255,255,.025);}
  .edu-tbl tr:hover td{background:rgba(127,212,255,.10);}
  .edu-tbl .num,.edu-tbl td.num{text-align:right;font-variant-numeric:tabular-nums;}

  /* ---------- grid de tarjetas ---------- */
  .edu-grid{display:flex;flex-wrap:wrap;gap:16px;margin:16px 0;}
  .edu-card{flex:1 1 220px;border-radius:16px;padding:18px 20px;
     background:linear-gradient(160deg,rgba(24,40,60,.6),rgba(13,23,37,.5));
     border:1px solid rgba(140,180,224,.16);transition:transform .18s ease,box-shadow .18s ease,border-color .18s ease;}
  .edu-card:hover{transform:translateY(-4px);box-shadow:0 16px 34px rgba(3,8,18,.5);border-color:rgba(127,212,255,.4);}
  .edu-card h3{margin:0 0 6px;}
  .edu-card p{margin:0;font-size:14px;color:#aebfd2;line-height:1.5;}

  /* ---------- KPIs / cifras ---------- */
  .edu-kpis{display:flex;flex-wrap:wrap;gap:14px;margin:18px 0;}
  .edu-kpi{flex:1 1 150px;text-align:center;border-radius:16px;padding:18px 14px;
     background:linear-gradient(165deg,rgba(20,38,58,.7),rgba(10,18,30,.6));
     border:1px solid rgba(140,180,224,.18);box-shadow:inset 0 1px 0 rgba(255,255,255,.05);}
  .edu-kpi .v{font-size:30px;font-weight:800;color:#7fd4ff;line-height:1;
     font-family:'Archivo Expanded','Archivo',sans-serif;text-shadow:0 0 22px rgba(127,212,255,.4);}
  .edu-kpi .l{font-size:10.5px;text-transform:uppercase;letter-spacing:1.2px;color:#8ea3ba;margin-top:8px;}

  /* ---------- callouts ---------- */
  .edu-note,.edu-warn,.edu-ok{border-radius:14px;padding:15px 20px;margin:16px 0;font-size:14px;
     line-height:1.62;border:1px solid;border-left-width:4px;backdrop-filter:blur(4px);}
  .edu-note{background:rgba(47,159,224,.10);border-color:rgba(127,212,255,.26);border-left-color:#7fd4ff;color:#cfe7fb;}
  .edu-warn{background:rgba(255,160,90,.10);border-color:rgba(255,180,110,.30);border-left-color:#ff9f5c;color:#ffd9b8;}
  .edu-ok{background:rgba(67,196,176,.10);border-color:rgba(90,220,190,.30);border-left-color:#43c4b0;color:#bff0e4;}
  .edu-note b,.edu-warn b,.edu-ok b{color:#fff;}

  /* ---------- spans destacados ---------- */
  .edu .hl{color:#7fd4ff;font-weight:700;} .edu .ok{color:#5ce0b5;font-weight:700;}
  .edu .warn{color:#ff9f5c;font-weight:700;}

  /* ---------- caption / pie ---------- */
  .edu-cap{font-size:12.5px;color:#8295ab;margin-top:12px;}
  .edu-foot{font-size:12.5px;color:#8295ab;margin-top:22px;border-top:1px dashed rgba(140,180,224,.22);padding-top:14px;}

  /* ---------- referencias ---------- */
  .edu-ref{background:rgba(8,16,28,.5);border:1px solid rgba(140,180,224,.16);border-left:4px solid #7fd4ff;
     border-radius:12px;padding:18px 20px;font-size:13.5px;color:#b9c8da;line-height:1.75;}

  /* ===================================================================
     PORTADA · HERO CINEMATOGRÁFICO
     =================================================================== */
  .edu-portada{max-width:1180px;margin:26px auto;border-radius:26px;overflow:hidden;
     font-family:'Archivo',system-ui,sans-serif;color:#e9f1fb;border:1px solid rgba(120,160,210,.18);
     box-shadow:0 40px 90px rgba(2,6,14,.6);animation:eduBreathe 12s ease-in-out infinite;}

  .edu-cine{position:relative;overflow:hidden;padding:26px 52px 24px 78px;min-height:560px;
     background:
        radial-gradient(60% 42% at 78% 6%,rgba(170,210,255,.20),transparent 55%),
        radial-gradient(80% 60% at 6% 104%,rgba(40,150,140,.20),transparent 60%),
        linear-gradient(180deg,#0c1a2b 0%,#0a1626 42%,#060f1b 100%);
     background-size:130% 130%,100% 100%,100% 100%;animation:eduHeroFlow 20s ease infinite;}

  /* atmósfera: niebla, grano, montañas, estrellas, cometas (todo CSS, sin imágenes externas) */
  .edu-fog{position:absolute;inset:0;z-index:0;pointer-events:none;
     background:radial-gradient(50% 38% at 50% 26%,rgba(150,190,230,.16),transparent 72%);filter:blur(14px);
     animation:eduFog 16s ease-in-out infinite;}
  .edu-grain{position:absolute;inset:0;z-index:2;pointer-events:none;opacity:.32;mix-blend-mode:overlay;
     background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='120' height='120'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='2' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E");}
  .edu-ridge{position:absolute;left:0;right:0;bottom:0;width:100%;height:190px;z-index:1;pointer-events:none;display:block;}
  .edu-stars,.edu-stars2{position:absolute;inset:0;pointer-events:none;z-index:1;}
  .edu-stars{animation:eduTwinkle 4.5s ease-in-out infinite;background-image:
     radial-gradient(1px 1px at 12% 22%,#fff,transparent),radial-gradient(1px 1px at 28% 64%,#fff,transparent),
     radial-gradient(1px 1px at 44% 14%,#fff,transparent),radial-gradient(1px 1px at 63% 38%,#fff,transparent),
     radial-gradient(1px 1px at 82% 33%,#fff,transparent),radial-gradient(1px 1px at 91% 20%,#fff,transparent),
     radial-gradient(1px 1px at 7% 48%,#fff,transparent),radial-gradient(1px 1px at 35% 12%,#fff,transparent);}
  .edu-stars2{animation:eduTwinkle 7s ease-in-out infinite;animation-delay:1.6s;background-image:
     radial-gradient(1.6px 1.6px at 18% 30%,#bfefff,transparent),radial-gradient(1.6px 1.6px at 49% 20%,#ffe9a8,transparent),
     radial-gradient(1.6px 1.6px at 70% 12%,#fff,transparent),radial-gradient(1.6px 1.6px at 88% 28%,#9fe6da,transparent),
     radial-gradient(1.6px 1.6px at 24% 18%,#fff,transparent);}
  .edu-comet{position:absolute;top:14%;left:-15%;width:160px;height:2px;z-index:1;pointer-events:none;
     background:linear-gradient(90deg,transparent,#bfefff,#fff);border-radius:50%;opacity:0;
     box-shadow:0 0 8px #bfefff,0 0 24px rgba(150,210,255,.55);transform:rotate(15deg);
     animation:eduComet 13s linear infinite;}
  .edu-comet.edu-comet2{top:40%;animation-duration:17s;animation-delay:7s;}

  .edu-cine>*{position:relative;z-index:3;}

  /* nav superior */
  .edu-nav{display:flex;justify-content:space-between;align-items:center;gap:18px;flex-wrap:wrap;
     padding-bottom:8px;border-bottom:1px solid rgba(160,195,235,.12);}
  .edu-logo{font-family:'Archivo Black',sans-serif;font-size:18px;letter-spacing:.5px;color:#fff;}
  .edu-logo span{color:#7fd4ff;font-weight:400;font-family:'Archivo',sans-serif;font-size:13px;margin-left:6px;letter-spacing:1px;}
  .edu-nav nav{display:flex;gap:22px;flex-wrap:wrap;}
  .edu-nav nav a{font-size:12.5px;letter-spacing:.6px;color:#aebfd2;text-decoration:none;text-transform:uppercase;
     font-weight:600;transition:color .15s ease;}
  .edu-nav nav a:hover{color:#fff;}
  .edu-nav nav a.on{color:#7fd4ff;}

  /* etiquetas verticales decorativas (borde izquierdo) */
  .edu-vlabels{position:absolute;left:20px;top:54%;transform:translateY(-50%);z-index:3;
     display:flex;flex-direction:column;gap:30px;}
  .edu-vlabels span{writing-mode:vertical-rl;transform:rotate(180deg);font-size:10px;letter-spacing:3px;
     text-transform:uppercase;color:rgba(174,191,210,.6);font-weight:600;
     font-family:'Archivo Expanded','Archivo',sans-serif;}

  /* layout principal: titular gigante a todo el ancho */
  .edu-cine-grid{margin-top:30px;}
  .edu-kicker{display:inline-block;font-family:'Archivo Expanded','Archivo',sans-serif;font-size:10.5px;
     font-weight:700;letter-spacing:3px;text-transform:uppercase;color:#8fb4d8;margin-bottom:18px;
     padding-left:2px;animation:eduRise .8s cubic-bezier(.2,.7,.2,1) both;}

  .edu-mega{font-family:'Archivo Black',sans-serif;text-transform:uppercase;color:#f6faff;margin:0;
     font-size:clamp(44px,6.6vw,92px);line-height:.9;letter-spacing:-.01em;
     text-shadow:0 1px 0 #c4cfdd,0 2px 0 #aeb9c9,0 3px 0 #99a5b8,0 4px 0 #8593a8,0 5px 0 #74829a,
                 0 12px 22px rgba(0,0,0,.6);animation:eduRise .9s cubic-bezier(.2,.7,.2,1) both;}
  .edu-mega em{display:block;font-style:normal;color:#7fd4ff;
     text-shadow:0 0 30px rgba(127,212,255,.55),0 3px 0 rgba(10,40,70,.5);}

  .edu-lede{max-width:480px;margin:24px 0 0;color:#c4d3e4;font-size:16px;line-height:1.6;
     animation:eduRise .9s cubic-bezier(.2,.7,.2,1) .15s both;}

  .edu-cta{display:inline-flex;align-items:center;gap:12px;margin-top:26px;cursor:pointer;
     padding:14px 26px;border-radius:999px;text-decoration:none;font-weight:700;font-size:14.5px;
     letter-spacing:.4px;color:#06121f;background:linear-gradient(135deg,#aee1ff,#7fd4ff);
     box-shadow:0 14px 34px rgba(127,212,255,.35);transition:transform .18s ease,box-shadow .18s ease;
     animation:eduRise .9s cubic-bezier(.2,.7,.2,1) .3s both;}
  .edu-cta:hover{transform:translateY(-2px);box-shadow:0 18px 42px rgba(127,212,255,.5);}
  .edu-cta span{transition:transform .18s ease;} .edu-cta:hover span{transform:translateX(5px);}

  /* tarjetas glassmorphic en fila horizontal (hallazgos) bajo el titular */
  .edu-floats{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px;margin-top:40px;}
  .edu-glass{position:relative;display:flex;flex-direction:column;border-radius:18px;padding:22px 24px;color:#e9f1fb;
     background:linear-gradient(160deg,rgba(22,38,58,.55),rgba(10,18,30,.42));
     backdrop-filter:blur(14px) saturate(130%);-webkit-backdrop-filter:blur(14px) saturate(130%);
     border:1px solid rgba(160,200,240,.18);box-shadow:0 20px 50px rgba(0,0,0,.45),inset 0 1px 0 rgba(255,255,255,.08);
     transition:transform .2s ease,border-color .2s ease;animation:eduRise .9s cubic-bezier(.2,.7,.2,1) both;}
  .edu-floats .edu-glass:nth-child(1){animation-delay:.35s;}
  .edu-floats .edu-glass:nth-child(2){animation-delay:.46s;}
  .edu-floats .edu-glass:nth-child(3){animation-delay:.57s;}
  .edu-glass:hover{transform:translateY(-4px);border-color:rgba(127,212,255,.5);}
  .edu-glass h4{margin:0 0 8px;font-size:17px;font-weight:700;color:#fff;font-family:'Archivo Expanded','Archivo',sans-serif;}
  .edu-glass p{margin:0;font-size:13.5px;line-height:1.55;color:#b6c6d8;}
  .edu-glass-foot{display:flex;justify-content:space-between;align-items:center;margin-top:auto;padding-top:16px;gap:10px;}
  .edu-metric{font-size:12px;font-weight:700;color:#7fd4ff;letter-spacing:.3px;}
  .edu-glass-foot a{font-size:12.5px;font-weight:700;color:#fff;text-decoration:none;white-space:nowrap;
     border-bottom:1px solid rgba(127,212,255,.5);padding-bottom:1px;transition:color .15s ease;}
  .edu-glass-foot a:hover{color:#7fd4ff;}

  /* fila de fuentes (logos) */
  .edu-logos{display:flex;align-items:center;gap:26px;flex-wrap:wrap;margin-top:38px;padding-top:18px;
     border-top:1px solid rgba(160,195,235,.12);}
  .edu-logos-label{font-size:10px;letter-spacing:2.5px;text-transform:uppercase;color:#6f86a0;font-weight:700;}
  .edu-logos>span:not(.edu-logos-label){font-family:'Archivo Expanded','Archivo',sans-serif;font-weight:700;
     font-size:13px;letter-spacing:.5px;color:rgba(190,205,222,.55);transition:color .18s ease;}
  .edu-logos>span:not(.edu-logos-label):hover{color:#cfe0f2;}

  /* franja de metadatos académicos bajo el hero */
  .edu-metastrip{background:linear-gradient(180deg,#0a131f,#0b1422);padding:26px 52px 30px;
     border-top:1px solid rgba(160,195,235,.10);}
  .edu-meta{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:18px;}
  .edu-meta>div{display:flex;flex-direction:column;gap:4px;}
  .edu-meta .k{font-size:10px;letter-spacing:1.8px;text-transform:uppercase;color:#7fd4ff;font-weight:700;
     font-family:'Archivo Expanded','Archivo',sans-serif;}
  .edu-meta .v{font-size:13.5px;color:#cdd9e7;line-height:1.45;}
  .edu-disc{background:rgba(255,170,90,.09);border:1px solid rgba(255,185,120,.28);border-left:4px solid #ff9f5c;
     color:#ffd9b8;border-radius:14px;padding:14px 18px;font-size:12.8px;margin-top:22px;line-height:1.6;}
  .edu-disc b{color:#ffe9d2;}

  @media (max-width:820px){
     .edu-cine{padding:24px 30px 22px;min-height:auto;}
     .edu-floats{grid-template-columns:1fr;gap:14px;margin-top:30px;}
     .edu-vlabels{display:none;}
     .edu-nav nav{gap:14px;} .edu-sheet{padding:26px 22px 30px;}
  }

  /* ===================================================================
     ANIMACIONES
     =================================================================== */
  @keyframes eduBarFlow{0%{background-position:0% 0;}100%{background-position:220% 0;}}
  @keyframes eduPulse{0%,100%{box-shadow:0 0 0 rgba(127,212,255,0);}50%{box-shadow:0 0 16px rgba(127,212,255,.35);}}
  @keyframes eduHeroFlow{0%{background-position:0% 50%,0 0,0 0;}50%{background-position:100% 50%,0 0,0 0;}100%{background-position:0% 50%,0 0,0 0;}}
  @keyframes eduBreathe{0%,100%{box-shadow:0 40px 90px rgba(2,6,14,.6);}50%{box-shadow:0 46px 104px rgba(20,80,110,.5);}}
  @keyframes eduTwinkle{0%,100%{opacity:.35;}50%{opacity:1;}}
  @keyframes eduFog{0%,100%{opacity:.7;transform:translateX(0);}50%{opacity:1;transform:translateX(20px);}}
  @keyframes eduComet{0%{opacity:0;transform:translate(0,0) rotate(15deg);}5%{opacity:.95;}
     22%{opacity:0;transform:translate(1200px,330px) rotate(15deg);}100%{opacity:0;}}
  @keyframes eduRise{from{opacity:0;transform:translateY(20px);}to{opacity:1;transform:translateY(0);}}

  @media (prefers-reduced-motion:reduce){
     .edu-portada,.edu-cine,.edu-fog,.edu-stars,.edu-stars2,.edu-comet,.edu-sheet::before,.edu-eyebrow,
     .edu-kicker,.edu-mega,.edu-lede,.edu-cta,.edu-glass{animation:none!important;}
  }
</style><style>
.edu-banner{position:relative;overflow:hidden;border-radius:20px;margin:26px auto;max-width:1140px;
  padding:28px 42px;color:#e9f1fb;font-family:'Archivo',system-ui,sans-serif;line-height:1.62;font-size:15px;
  background:radial-gradient(72% 130% at 90% -25%,rgba(127,212,255,.16),transparent 60%),
             radial-gradient(80% 120% at 0% 132%,rgba(40,150,140,.14),transparent 60%),
             linear-gradient(168deg,#0c1a2b,#0a1626 58%,#060f1b);
  border:1px solid rgba(140,180,224,.16);box-shadow:0 30px 70px rgba(3,8,18,.5),inset 0 1px 0 rgba(255,255,255,.05);}
.edu-banner::before{content:"";position:absolute;top:0;left:0;right:0;height:4px;z-index:2;
  background:linear-gradient(90deg,#1d6fb0,#43c4b0 35%,#7fd4ff 55%,#43c4b0 75%,#1d6fb0);
  background-size:220% 100%;animation:eduBarFlow 7s linear infinite;}
.edu-banner>*{position:relative;z-index:1;}
.edu-banner .eb{display:inline-block;font-family:'Archivo Expanded','Archivo',sans-serif;font-size:10.5px;
  font-weight:700;letter-spacing:3px;text-transform:uppercase;color:#7fd4ff;
  background:rgba(127,212,255,.08);border:1px solid rgba(127,212,255,.30);padding:5px 15px;border-radius:999px;
  animation:eduPulse 3.4s ease-in-out infinite;}
.edu-banner h2{font-family:'Archivo Black',sans-serif;text-transform:uppercase;color:#f6faff;
  margin:15px 0 0;font-size:clamp(24px,3.2vw,38px);line-height:.96;letter-spacing:-.01em;
  text-shadow:0 2px 0 #8593a8,0 8px 18px rgba(0,0,0,.5);animation:eduRise .7s cubic-bezier(.2,.7,.2,1) both;}
.edu-banner h2 em{font-style:normal;color:#7fd4ff;text-shadow:0 0 26px rgba(127,212,255,.5);}
.edu-banner .lede{margin:14px 0 0;max-width:700px;color:#c4d3e4;font-size:15px;}
.edu-banner .step{position:absolute;right:34px;top:50%;transform:translateY(-50%);z-index:0;
  font-family:'Archivo Black',sans-serif;font-size:104px;line-height:1;color:rgba(127,212,255,.09);}
.edu-banner h3{font-family:'Archivo Expanded','Archivo',sans-serif;color:#7fd4ff;font-size:12px;
  letter-spacing:1.4px;text-transform:uppercase;margin:22px 0 6px;}
.edu-banner p{margin:8px 0;color:#cdd9e7;} .edu-banner b{color:#fff;}
.edu-banner ul{margin:10px 0 0;padding-left:2px;list-style:none;}
.edu-banner ul li{position:relative;padding-left:24px;margin:9px 0;color:#cdd9e7;}
.edu-banner ul li::before{content:"";position:absolute;left:3px;top:8px;width:8px;height:8px;border-radius:2px;
  background:linear-gradient(135deg,#7fd4ff,#43c4b0);transform:rotate(45deg);box-shadow:0 0 8px rgba(127,212,255,.5);}
.edu-banner .row{display:flex;gap:16px;margin:12px 0;padding:14px 18px;border-radius:13px;
  background:rgba(8,16,28,.5);border:1px solid rgba(140,180,224,.14);border-left:3px solid #43c4b0;}
.edu-banner .row.alt{border-left-color:#ff9f5c;}
.edu-banner .row .k{flex:0 0 132px;font:700 11px/1.5 'Archivo Expanded','Archivo',sans-serif;letter-spacing:1px;
  text-transform:uppercase;color:#ff9f5c;}
.edu-banner .row .v{flex:1;color:#dde7f2;font-size:14.5px;}
.edu-banner .foot{margin-top:22px;border-top:1px dashed rgba(140,180,224,.22);padding-top:13px;
  font-size:12.5px;color:#8295ab;}
@media (max-width:820px){.edu-banner{padding:22px 24px;} .edu-banner .step{display:none;}
  .edu-banner .row{flex-direction:column;gap:4px;} .edu-banner .row .k{flex:none;}}
</style><div style="filter:hue-rotate(118deg) saturate(0.95);"><div class="edu-portada">
  <div class="edu-cine">
     <div class="edu-fog"></div><div class="edu-stars"></div><div class="edu-stars2"></div>
     <span class="edu-comet"></span><span class="edu-comet edu-comet2"></span>
     <svg class="edu-ridge" viewBox="0 0 1200 200" preserveAspectRatio="none" aria-hidden="true">
        <defs><linearGradient id="eduRg" x1="0" y1="0" x2="0" y2="1">
        <stop offset="0" stop-color="#0d2034"/><stop offset="1" stop-color="#050b14"/></linearGradient></defs>
        <path d="M0,200 L0,118 L130,72 L250,112 L380,52 L520,118 L660,58 L800,116 L940,46 L1070,104 L1200,64 L1200,200 Z" fill="url(#eduRg)"/>
     </svg>
     <div class="edu-grain"></div>
     <header class="edu-nav"><div class="edu-logo">ds-colabs<span>· IA aplicada &amp; Agentes</span></div></header>
     <div class="edu-vlabels"><span>Dígitos 8×8</span><span>CNN PyTorch</span><span>Accuracy</span></div>
     <div class="edu-cine-grid"><div class="edu-cine-main">
        <span class="edu-kicker">IA aplicada &amp; Agentes · Visión por computadora</span>
        <h1 class="edu-mega">CNN para clasificar dígitos</h1>
        <p class="edu-lede">Una red convolucional chica en PyTorch (CPU) contra un baseline lineal sobre los píxeles.</p>
        <a class="edu-cta" href="#">Explorar el análisis <span>&rarr;</span></a>
     </div>
     <aside class="edu-floats"><article class="edu-glass"><h4>Problema</h4><p>Clasificar dígitos 0–9 a partir de imágenes diminutas de 8×8 píxeles en escala de grises.</p><div class="edu-glass-foot"><span class="edu-metric">Visión 2D</span><a>Ver análisis &rarr;</a></div></article><article class="edu-glass"><h4>Enfoque</h4><p>Una CNN chica que aprende filtros espaciales, frente a un baseline lineal sobre píxeles planos.</p><div class="edu-glass-foot"><span class="edu-metric">CNN vs lineal</span><a>Ver análisis &rarr;</a></div></article><article class="edu-glass"><h4>Métrica</h4><p>Accuracy en test y matriz de confusión para ver qué dígitos se confunden.</p><div class="edu-glass-foot"><span class="edu-metric">Accuracy</span><a>Ver análisis &rarr;</a></div></article></aside></div>
     <div class="edu-logos"><span class="edu-logos-label">Fuentes</span><span>scikit-learn</span><span>PyTorch</span><span>Plotly</span><span>Google Colab</span></div>
  </div>
  <div class="edu-metastrip"><div class="edu-meta"><div><span class="k">Autor</span><span class="v">Nicolás Bargioni</span></div><div><span class="k">Rol</span><span class="v">Data Scientist</span></div><div><span class="k">Categoría</span><span class="v">IA aplicada &amp; Agentes</span></div><div><span class="k">Dataset</span><span class="v">load_digits (1797 imágenes 8×8 en escala de grises)</span></div></div></div>
</div></div>'''))

## 🧭 Marco del trabajo

| | |
|---|---|
| **Objetivo** | Entrenar una CNN chica en CPU para clasificar dígitos 8×8 y compararla contra un baseline de regresión logística sobre los píxeles planos. |
| **Hipótesis** | La CNN, al explotar la estructura espacial 2D con filtros convolucionales, iguala o supera a un clasificador lineal que trata cada píxel como una feature independiente. |
| **Datos** | Las 1797 imágenes 8×8 (16 niveles de gris) del dataset load_digits de scikit-learn, una versión reducida del clásico MNIST de la UCI. |
| **Metodología** | load_digits → split estratificado (random_state=42) → normalización → tensores 1×8×8 → CNN entrenada con Adam/CrossEntropy → evaluación (accuracy, matriz de confusión) vs baseline LogisticRegression. |
| **Métrica** | Accuracy en test + matriz de confusión |

> Ejecutable top-down · `random_state=42` · preprocesamiento **sin data leakage**.

## 🛠 0 · Setup

Imports (PyTorch, scikit-learn, Plotly), semilla fija y device CPU.

In [2]:
import warnings; warnings.filterwarnings('ignore')
import numpy as np
import torch, torch.nn as nn, torch.nn.functional as F
from torch.utils.data import TensorDataset, DataLoader
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
import plotly.express as px, plotly.graph_objects as go, plotly.io as pio
from plotly.subplots import make_subplots
pio.templates.default = 'plotly_dark'

SEED = 42
torch.manual_seed(SEED); np.random.seed(SEED)
DEVICE = torch.device('cpu')          # corre 100% en CPU; no requiere GPU
PRIMARY, ACCENT = '#7fd4ff', '#ff9f5c'
print('Setup OK · PyTorch', torch.__version__, '· device =', DEVICE)
print('Hilos CPU disponibles para torch:', torch.get_num_threads())

Setup OK · PyTorch 2.10.0 · device = cpu
Hilos CPU disponibles para torch: 4


## 🔢 1 · Datos

Cargamos `load_digits` (1797 imágenes 8×8), las miramos, hacemos el split estratificado, normalizamos sin leakage y armamos tensores 1×8×8.

In [3]:
# 1a · Cargar el dataset y mirar su forma
digits = load_digits()
X_img, y = digits.images, digits.target          # X_img: (1797, 8, 8) en [0, 16]
print('Imágenes:', X_img.shape, '· rango de intensidad:', X_img.min(), '-', X_img.max())
print('Etiquetas:', y.shape, '· clases:', np.unique(y))
print('Ejemplos por clase:', np.bincount(y))      # dataset balanceado

Imágenes: (1797, 8, 8) · rango de intensidad: 0.0 - 16.0
Etiquetas: (1797,) · clases: [0 1 2 3 4 5 6 7 8 9]
Ejemplos por clase: [178 182 177 183 181 182 181 179 174 180]


In [4]:
# 1b · Mostrar un ejemplo de cada dígito (heatmaps Plotly)
fig = make_subplots(rows=2, cols=5,
                    subplot_titles=[f'dígito {d}' for d in range(10)],
                    horizontal_spacing=0.04, vertical_spacing=0.12)
for d in range(10):
    idx = np.where(y == d)[0][0]                  # primer ejemplo de cada clase
    r, c = divmod(d, 5)
    fig.add_trace(go.Heatmap(z=X_img[idx][::-1], colorscale='Blues',
                             showscale=False), row=r+1, col=c+1)
fig.update_xaxes(visible=False); fig.update_yaxes(visible=False)
fig.update_layout(height=420, title='Un ejemplo de cada dígito (8×8 píxeles, 0–16 niveles de gris)')
fig.show()

In [5]:
# 1c · Split estratificado + normalización + tensores 1×8×8
# Split ANTES de calcular estadísticas → sin data leakage.
X_flat = X_img.reshape(len(X_img), -1)            # (1797, 64) para el baseline y el split
Xtr_f, Xte_f, ytr, yte = train_test_split(
    X_flat, y, test_size=0.25, stratify=y, random_state=SEED)

# Normalización: media/desvío calculados SOLO con train, aplicados a ambos.
mu, sigma = Xtr_f.mean(), Xtr_f.std()
Xtr_n = (Xtr_f - mu) / sigma
Xte_n = (Xte_f - mu) / sigma

# A tensores con forma (N, C=1, H=8, W=8) que es lo que espera Conv2d.
Xtr_t = torch.tensor(Xtr_n, dtype=torch.float32).reshape(-1, 1, 8, 8)
Xte_t = torch.tensor(Xte_n, dtype=torch.float32).reshape(-1, 1, 8, 8)
ytr_t = torch.tensor(ytr, dtype=torch.long)
yte_t = torch.tensor(yte, dtype=torch.long)

train_dl = DataLoader(TensorDataset(Xtr_t, ytr_t), batch_size=64, shuffle=True)
print(f'Train: {Xtr_t.shape}  ·  Test: {Xte_t.shape}')
print(f'Normalización (solo train) → media={mu:.3f}, desvío={sigma:.3f}')

Train: torch.Size([1347, 1, 8, 8])  ·  Test: torch.Size([450, 1, 8, 8])
Normalización (solo train) → media=4.889, desvío=6.015


## 🧠 2 · Modelo

Una CNN chica: Conv2d→ReLU→MaxPool → Conv2d→ReLU→MaxPool → Flatten → Linear.

In [6]:
# 2 · La CNN: dos bloques convolucionales + clasificador lineal
class DigitCNN(nn.Module):
    def __init__(self, n_classes=10):
        super().__init__()
        # Conv1: 1 canal de entrada → 8 filtros 3×3, padding=1 conserva el tamaño (8×8).
        #        Cada filtro aprende un detector local (bordes, esquinas, trazos).
        self.conv1 = nn.Conv2d(in_channels=1,  out_channels=8,  kernel_size=3, padding=1)
        # Conv2: 8 → 16 filtros 3×3. Opera sobre el mapa ya reducido (4×4) y combina
        #        las features de bajo nivel en patrones más complejos.
        self.conv2 = nn.Conv2d(in_channels=8,  out_channels=16, kernel_size=3, padding=1)
        self.pool  = nn.MaxPool2d(2)              # reduce a la mitad H y W (downsampling)
        # Tras conv1→pool: 8×(4×4). Tras conv2→pool: 16×(2×2) = 64 valores aplanados.
        self.fc    = nn.Linear(16 * 2 * 2, n_classes)

    def forward(self, x):                         # x: (N, 1, 8, 8)
        x = self.pool(F.relu(self.conv1(x)))      # → (N, 8, 4, 4)
        x = self.pool(F.relu(self.conv2(x)))      # → (N, 16, 2, 2)
        x = x.flatten(1)                          # → (N, 64)
        return self.fc(x)                         # logits → (N, 10)

model = DigitCNN().to(DEVICE)
n_params = sum(p.numel() for p in model.parameters())
print(model)
print(f'\nParámetros entrenables: {n_params:,}')

DigitCNN(
  (conv1): Conv2d(1, 8, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (conv2): Conv2d(8, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (pool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (fc): Linear(in_features=64, out_features=10, bias=True)
)

Parámetros entrenables: 1,898


**Anatomía de la red, capa por capa.**

- **`Conv2d(1→8, 3×3)`** desliza 8 filtros de 3×3 sobre la imagen. Cada filtro es un detector local de patrones de bajo nivel (un borde inclinado, una esquina, un trazo). El `padding=1` mantiene el tamaño 8×8 para no perder los bordes. La salida son 8 *mapas de activación* que dicen *dónde* aparece cada patrón.
- **`ReLU`** introduce no linealidad (pone en cero las activaciones negativas). Sin ella, apilar convoluciones colapsaría en una sola transformación lineal.
- **`MaxPool2d(2)`** se queda con el máximo de cada ventana 2×2: reduce la resolución a la mitad (8×8 → 4×4), da algo de invariancia a pequeños desplazamientos y baja el cómputo.
- **`Conv2d(8→16, 3×3)`** actúa sobre los mapas ya reducidos: combina las features simples en patrones más complejos (combinaciones de trazos que forman parte de un dígito). Tras su pooling quedan 16 mapas de 2×2.
- **`Flatten`** estira esos 16×2×2 = 64 valores en un vector.
- **`Linear(64→10)`** es el clasificador: produce un *logit* por clase. El más alto es la predicción.

La idea clave es la **jerarquía de features**: las primeras capas ven detalles locales, las siguientes los combinan en estructuras cada vez más abstractas. Es la diferencia con un modelo lineal sobre píxeles, que trata cada píxel como una variable suelta sin noción de vecindad espacial.

## 🏋️ 3 · Entrenamiento

Loop de 20 épocas en CPU con Adam y CrossEntropy; guardamos loss y accuracy por época.

In [7]:
# 3 · Entrenamiento en CPU (Adam + CrossEntropy)
EPOCHS = 20
opt = torch.optim.Adam(model.parameters(), lr=1e-3)
crit = nn.CrossEntropyLoss()                       # combina log-softmax + NLL

loss_hist, acc_hist = [], []
for ep in range(1, EPOCHS + 1):
    model.train(); running = 0.0
    for xb, yb in train_dl:
        opt.zero_grad()
        loss = crit(model(xb), yb)
        loss.backward(); opt.step()
        running += loss.item() * len(xb)
    epoch_loss = running / len(train_dl.dataset)
    # accuracy en train (rápido, sin gradientes) para ver el aprendizaje
    model.eval()
    with torch.no_grad():
        tr_acc = (model(Xtr_t).argmax(1) == ytr_t).float().mean().item()
    loss_hist.append(epoch_loss); acc_hist.append(tr_acc)
    if ep % 4 == 0 or ep == 1:
        print(f'época {ep:2d}/{EPOCHS} · loss={epoch_loss:.4f} · acc_train={tr_acc:.4f}')
print('\nEntrenamiento terminado.')

época  1/20 · loss=2.2602 · acc_train=0.3534
época  4/20 · loss=1.7462 · acc_train=0.7996


época  8/20 · loss=0.5810 · acc_train=0.9109


época 12/20 · loss=0.2719 · acc_train=0.9488


época 16/20 · loss=0.1830 · acc_train=0.9651


época 20/20 · loss=0.1237 · acc_train=0.9703

Entrenamiento terminado.


In [8]:
# 3b · Curva de loss y accuracy de entrenamiento por época
fig = make_subplots(specs=[[{'secondary_y': True}]])
ep_axis = list(range(1, EPOCHS + 1))
fig.add_trace(go.Scatter(x=ep_axis, y=loss_hist, name='Loss (train)',
                         line=dict(color=ACCENT, width=3)), secondary_y=False)
fig.add_trace(go.Scatter(x=ep_axis, y=acc_hist, name='Accuracy (train)',
                         line=dict(color=PRIMARY, width=3)), secondary_y=True)
fig.update_xaxes(title_text='Época')
fig.update_yaxes(title_text='CrossEntropy loss', secondary_y=False)
fig.update_yaxes(title_text='Accuracy', secondary_y=True, range=[0, 1.01])
fig.update_layout(title='Curva de entrenamiento de la CNN (CPU, 20 épocas)', height=420)
fig.show()

## 📊 4 · Evaluación

Accuracy en test, matriz de confusión y comparación contra un baseline de regresión logística sobre los píxeles planos.

In [9]:
# 4 · Evaluación en test: CNN vs baseline lineal
# --- CNN ---
model.eval()
with torch.no_grad():
    cnn_pred = model(Xte_t).argmax(1).numpy()
acc_cnn = accuracy_score(yte, cnn_pred)

# --- Baseline: regresión logística sobre los 64 píxeles planos (mismos datos normalizados) ---
logreg = LogisticRegression(max_iter=2000, random_state=SEED)
logreg.fit(Xtr_n, ytr)
base_pred = logreg.predict(Xte_n)
acc_base = accuracy_score(yte, base_pred)

print(f'Accuracy CNN (PyTorch)            : {acc_cnn:.4f}')
print(f'Accuracy baseline (LogisticReg)   : {acc_base:.4f}')
print(f'Diferencia (CNN - baseline)       : {acc_cnn - acc_base:+.4f}')

Accuracy CNN (PyTorch)            : 0.9467
Accuracy baseline (LogisticReg)   : 0.9667
Diferencia (CNN - baseline)       : -0.0200


In [10]:
# 4b · Matriz de confusión de la CNN (Plotly heatmap)
cm = confusion_matrix(yte, cnn_pred)
fig = px.imshow(cm, text_auto=True, color_continuous_scale='Blues',
                labels=dict(x='Predicho', y='Real', color='Conteo'),
                x=[str(d) for d in range(10)], y=[str(d) for d in range(10)],
                title=f'Matriz de confusión · CNN (accuracy test = {acc_cnn:.3f})')
fig.update_layout(height=520, coloraxis_showscale=True)
fig.show()

# Resumir los errores fuera de la diagonal (qué se confunde con qué)
errs = [(yte_lbl, pred_lbl, int(cm[yte_lbl, pred_lbl]))
        for yte_lbl in range(10) for pred_lbl in range(10)
        if yte_lbl != pred_lbl and cm[yte_lbl, pred_lbl] > 0]
errs.sort(key=lambda t: -t[2])
print('Confusiones más frecuentes (real → predicho : conteo):')
for real, pred, n in errs[:6]:
    print(f'  {real} → {pred} : {n}')
print(f'Total de errores de la CNN en test: {(cnn_pred != yte).sum()} de {len(yte)}')

Confusiones más frecuentes (real → predicho : conteo):
  8 → 1 : 4
  1 → 2 : 2
  2 → 1 : 2
  3 → 2 : 2
  5 → 9 : 2
  0 → 4 : 1
Total de errores de la CNN en test: 24 de 450


**Cómo leer la comparación.** La CNN y el baseline se evalúan sobre exactamente el mismo test set y los mismos datos normalizados, así que la diferencia mide solo el aporte de la arquitectura convolucional. La **matriz de confusión** pone los aciertos en la diagonal; todo lo que cae fuera son errores, y su posición dice *qué* dígito se confundió con cuál. Los errores típicos no son aleatorios: aparecen entre dígitos que comparten trazos a resolución 8×8 (donde la imagen es tan chica que algunas formas quedan casi idénticas). Por eso conviene mirar las celdas fuera de la diagonal más que la accuracy global.

### 📌 Lectura de resultados

Entrenamos la CNN **20 épocas en CPU** (1.898 parámetros, ~8 s de ejecución total del notebook) sobre 1.347 imágenes de train y la evaluamos sobre 450 de test. Estos son los números reales:

| Modelo | Accuracy en test | Errores (de 450) |
|---|---|---|
| Baseline · `LogisticRegression` (64 píxeles planos) | **0.9667** | 15 |
| CNN · PyTorch (Conv→ReLU→Pool ×2 → Linear) | **0.9467** | 24 |

**Qué dicen los números (y por qué contradicen la intuición "CNN gana siempre").**

- La curva de entrenamiento es sana: la loss baja de **2.26 → 0.12** y la accuracy de train sube de 0.35 a **0.970** sin estancarse ni dispararse. La CNN *aprende*, no hay un bug.
- Pero en test el **baseline lineal gana por 2 puntos** (96.7% vs 94.7%). La hipótesis —que la convolución igualaría o superaría al modelo lineal— **no se cumple acá**, y el motivo es instructivo: a **8×8 píxeles** el dataset `load_digits` es casi *linealmente separable*. Con solo 64 features y 10 clases bien balanceadas, una regresión logística tiene margen de sobra para trazar fronteras limpias, mientras que la CNN —con su pooling agresivo que reduce 8×8 a 2×2— **tira mucha resolución espacial** justo cuando hay poquísima para empezar. El sesgo inductivo convolucional (localidad, invariancia a traslación) recién paga cuando las imágenes son grandes y los patrones se repiten por toda la escena: MNIST 28×28, y sobre todo imágenes naturales.
- La **matriz de confusión** confirma que los 24 errores no son ruido aleatorio: se concentran en pares de dígitos que comparten trazos a esta resolución diminuta. El error más frecuente es **8 → 1 (4 veces)**, seguido de confusiones recíprocas **1↔2** y **3→2** (2 cada una) y **5→9**. Son justamente los dígitos cuyas formas, comprimidas a 8×8, dejan de ser distinguibles.

**Lectura honesta:** el experimento no "falla" — enseña *cuándo* una CNN aporta y cuándo no. Con datos de juguete y baja resolución, un baseline lineal fuerte es difícil de batir y debe ser siempre el punto de comparación. La ventaja de la CNN se haría visible escalando a 28×28 con torchvision, agregando dropout/batch-norm y data augmentation: ahí la jerarquía de features convolucional empieza a despegar.

## ✅ Conclusiones

- Una **CNN chica** (dos convoluciones + una capa lineal) clasifica dígitos 8×8 con alta precisión entrenando enteramente en **CPU** en segundos.
- Con imágenes tan pequeñas (8×8) el **baseline lineal gana** (96.7% vs 94.7% de la CNN): el dataset es casi linealmente separable, así que la convolución no despega como sí lo haría en MNIST 28×28 o en imágenes naturales.
- La **matriz de confusión** revela los pares de dígitos que comparten trazos (típicamente confusiones entre formas parecidas), no errores aleatorios.
- Próximos pasos: probar en MNIST 28×28 (con torchvision), agregar dropout/batch-norm y data augmentation para ver crecer la ventaja de la CNN.

---
*Nicolás Bargioni · Data Scientist · [nicolasbargioni.com](https://nicolasbargioni.com)*