# Q-learning en Taxi
*Reinforcement Learning (Q-learning tabular) · Data & Machine Learning*

In [1]:
#@title 📌 Portada
from IPython.display import HTML, display
display(HTML(r'''<style>
  @import url('https://fonts.googleapis.com/css2?family=Archivo+Black&family=Archivo:wght@400;500;600;700&family=Archivo+Expanded:wght@600;700;800&display=swap');

  /* ===================================================================
     SISTEMA EDITORIAL CINEMATOGRÁFICO OSCURO
     Paleta fría documental · tipografía display extruida · vidrio esmerilado
     =================================================================== */

  /* ---------- contenedor base ---------- */
  .edu{max-width:1140px;margin:24px auto;font-family:'Archivo',system-ui,sans-serif;
       color:#dde7f2;line-height:1.66;font-size:15px;}
  .edu *{box-sizing:border-box;}

  /* ---------- hoja: panel de vidrio oscuro ---------- */
  .edu-sheet{position:relative;overflow:hidden;border-radius:22px;padding:36px 44px 40px;
     color:#e6eef8;background:linear-gradient(168deg,rgba(17,30,47,.94),rgba(9,16,27,.96));
     border:1px solid rgba(140,180,224,.14);
     box-shadow:0 30px 70px rgba(3,8,18,.55),inset 0 1px 0 rgba(255,255,255,.05);}
  .edu-sheet::before{content:"";position:absolute;top:0;left:0;right:0;height:4px;
     background:linear-gradient(90deg,#1d6fb0,#43c4b0 35%,#7fd4ff 55%,#43c4b0 75%,#1d6fb0);
     background-size:220% 100%;animation:eduBarFlow 7s linear infinite;}
  .edu-sheet::after{content:"";position:absolute;inset:0;pointer-events:none;z-index:0;opacity:.5;
     background:radial-gradient(110% 60% at 88% -10%,rgba(127,212,255,.10),transparent 60%);}
  .edu-sheet>*{position:relative;z-index:1;}

  /* ---------- eyebrow / etiqueta ---------- */
  .edu-eyebrow{display:inline-block;font-family:'Archivo Expanded','Archivo',sans-serif;
     font-size:10.5px;font-weight:700;letter-spacing:3px;text-transform:uppercase;color:#7fd4ff;
     background:rgba(127,212,255,.08);border:1px solid rgba(127,212,255,.30);
     padding:6px 16px;border-radius:999px;margin-bottom:18px;animation:eduPulse 3.4s ease-in-out infinite;}

  /* ---------- títulos ---------- */
  .edu h2{font-family:'Archivo Expanded','Archivo',sans-serif;color:#f1f7ff;font-size:23px;
     font-weight:800;letter-spacing:.3px;text-transform:uppercase;margin:34px 0 14px;
     padding:6px 0 10px 18px;border-left:4px solid #43c4b0;
     background:linear-gradient(90deg,rgba(67,196,176,.12),transparent 60%);}
  .edu h2:first-child{margin-top:0;}
  .edu h2.alt{border-left-color:#ff8f6b;background:linear-gradient(90deg,rgba(255,143,107,.13),transparent 60%);}
  .edu h3{color:#7fd4ff;font-size:12px;font-weight:700;letter-spacing:1.4px;
     text-transform:uppercase;margin:22px 0 6px;font-family:'Archivo Expanded','Archivo',sans-serif;}
  .edu p{margin:9px 0;color:#cdd9e7;}
  .edu b,.edu strong{color:#ffffff;font-weight:700;}
  .edu i,.edu em{color:#bfe6ff;}
  .edu code{background:rgba(127,212,255,.12);border:1px solid rgba(127,212,255,.26);border-radius:5px;
     padding:1px 7px;font-size:13px;color:#bfe6ff;font-family:ui-monospace,Menlo,monospace;}

  /* ---------- listas con viñeta propia ---------- */
  .edu ul{margin:6px 0;padding-left:2px;list-style:none;}
  .edu ul li{position:relative;padding-left:26px;margin:8px 0;color:#cdd9e7;}
  .edu ul li::before{content:"";position:absolute;left:4px;top:9px;width:8px;height:8px;border-radius:2px;
     background:linear-gradient(135deg,#7fd4ff,#43c4b0);transform:rotate(45deg);box-shadow:0 0 8px rgba(127,212,255,.5);}

  /* ---------- tablas ---------- */
  .edu-tbl{border-collapse:separate;border-spacing:0;width:100%;font-size:14px;margin:16px 0;
     border:1px solid rgba(140,180,224,.16);border-radius:14px;overflow:hidden;
     background:rgba(8,15,26,.45);box-shadow:0 10px 30px rgba(3,8,18,.4);}
  .edu-tbl th{background:linear-gradient(135deg,#103a5e,#1c6aa6);color:#eaf4ff;font-weight:700;
     padding:12px 15px;text-align:left;letter-spacing:.4px;border:none;
     font-family:'Archivo Expanded','Archivo',sans-serif;font-size:12px;text-transform:uppercase;}
  .edu-tbl td{padding:10px 15px;border:none;border-top:1px solid rgba(140,180,224,.10);color:#d4e0ee;}
  .edu-tbl tr:nth-child(even) td{background:rgba(255,255,255,.025);}
  .edu-tbl tr:hover td{background:rgba(127,212,255,.10);}
  .edu-tbl .num,.edu-tbl td.num{text-align:right;font-variant-numeric:tabular-nums;}

  /* ---------- grid de tarjetas ---------- */
  .edu-grid{display:flex;flex-wrap:wrap;gap:16px;margin:16px 0;}
  .edu-card{flex:1 1 220px;border-radius:16px;padding:18px 20px;
     background:linear-gradient(160deg,rgba(24,40,60,.6),rgba(13,23,37,.5));
     border:1px solid rgba(140,180,224,.16);transition:transform .18s ease,box-shadow .18s ease,border-color .18s ease;}
  .edu-card:hover{transform:translateY(-4px);box-shadow:0 16px 34px rgba(3,8,18,.5);border-color:rgba(127,212,255,.4);}
  .edu-card h3{margin:0 0 6px;}
  .edu-card p{margin:0;font-size:14px;color:#aebfd2;line-height:1.5;}

  /* ---------- KPIs / cifras ---------- */
  .edu-kpis{display:flex;flex-wrap:wrap;gap:14px;margin:18px 0;}
  .edu-kpi{flex:1 1 150px;text-align:center;border-radius:16px;padding:18px 14px;
     background:linear-gradient(165deg,rgba(20,38,58,.7),rgba(10,18,30,.6));
     border:1px solid rgba(140,180,224,.18);box-shadow:inset 0 1px 0 rgba(255,255,255,.05);}
  .edu-kpi .v{font-size:30px;font-weight:800;color:#7fd4ff;line-height:1;
     font-family:'Archivo Expanded','Archivo',sans-serif;text-shadow:0 0 22px rgba(127,212,255,.4);}
  .edu-kpi .l{font-size:10.5px;text-transform:uppercase;letter-spacing:1.2px;color:#8ea3ba;margin-top:8px;}

  /* ---------- callouts ---------- */
  .edu-note,.edu-warn,.edu-ok{border-radius:14px;padding:15px 20px;margin:16px 0;font-size:14px;
     line-height:1.62;border:1px solid;border-left-width:4px;backdrop-filter:blur(4px);}
  .edu-note{background:rgba(47,159,224,.10);border-color:rgba(127,212,255,.26);border-left-color:#7fd4ff;color:#cfe7fb;}
  .edu-warn{background:rgba(255,160,90,.10);border-color:rgba(255,180,110,.30);border-left-color:#ff9f5c;color:#ffd9b8;}
  .edu-ok{background:rgba(67,196,176,.10);border-color:rgba(90,220,190,.30);border-left-color:#43c4b0;color:#bff0e4;}
  .edu-note b,.edu-warn b,.edu-ok b{color:#fff;}

  /* ---------- spans destacados ---------- */
  .edu .hl{color:#7fd4ff;font-weight:700;} .edu .ok{color:#5ce0b5;font-weight:700;}
  .edu .warn{color:#ff9f5c;font-weight:700;}

  /* ---------- caption / pie ---------- */
  .edu-cap{font-size:12.5px;color:#8295ab;margin-top:12px;}
  .edu-foot{font-size:12.5px;color:#8295ab;margin-top:22px;border-top:1px dashed rgba(140,180,224,.22);padding-top:14px;}

  /* ---------- referencias ---------- */
  .edu-ref{background:rgba(8,16,28,.5);border:1px solid rgba(140,180,224,.16);border-left:4px solid #7fd4ff;
     border-radius:12px;padding:18px 20px;font-size:13.5px;color:#b9c8da;line-height:1.75;}

  /* ===================================================================
     PORTADA · HERO CINEMATOGRÁFICO
     =================================================================== */
  .edu-portada{max-width:1180px;margin:26px auto;border-radius:26px;overflow:hidden;
     font-family:'Archivo',system-ui,sans-serif;color:#e9f1fb;border:1px solid rgba(120,160,210,.18);
     box-shadow:0 40px 90px rgba(2,6,14,.6);animation:eduBreathe 12s ease-in-out infinite;}

  .edu-cine{position:relative;overflow:hidden;padding:26px 52px 24px 78px;min-height:560px;
     background:
        radial-gradient(60% 42% at 78% 6%,rgba(170,210,255,.20),transparent 55%),
        radial-gradient(80% 60% at 6% 104%,rgba(40,150,140,.20),transparent 60%),
        linear-gradient(180deg,#0c1a2b 0%,#0a1626 42%,#060f1b 100%);
     background-size:130% 130%,100% 100%,100% 100%;animation:eduHeroFlow 20s ease infinite;}

  /* atmósfera: niebla, grano, montañas, estrellas, cometas (todo CSS, sin imágenes externas) */
  .edu-fog{position:absolute;inset:0;z-index:0;pointer-events:none;
     background:radial-gradient(50% 38% at 50% 26%,rgba(150,190,230,.16),transparent 72%);filter:blur(14px);
     animation:eduFog 16s ease-in-out infinite;}
  .edu-grain{position:absolute;inset:0;z-index:2;pointer-events:none;opacity:.32;mix-blend-mode:overlay;
     background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='120' height='120'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='2' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E");}
  .edu-ridge{position:absolute;left:0;right:0;bottom:0;width:100%;height:190px;z-index:1;pointer-events:none;display:block;}
  .edu-stars,.edu-stars2{position:absolute;inset:0;pointer-events:none;z-index:1;}
  .edu-stars{animation:eduTwinkle 4.5s ease-in-out infinite;background-image:
     radial-gradient(1px 1px at 12% 22%,#fff,transparent),radial-gradient(1px 1px at 28% 64%,#fff,transparent),
     radial-gradient(1px 1px at 44% 14%,#fff,transparent),radial-gradient(1px 1px at 63% 38%,#fff,transparent),
     radial-gradient(1px 1px at 82% 33%,#fff,transparent),radial-gradient(1px 1px at 91% 20%,#fff,transparent),
     radial-gradient(1px 1px at 7% 48%,#fff,transparent),radial-gradient(1px 1px at 35% 12%,#fff,transparent);}
  .edu-stars2{animation:eduTwinkle 7s ease-in-out infinite;animation-delay:1.6s;background-image:
     radial-gradient(1.6px 1.6px at 18% 30%,#bfefff,transparent),radial-gradient(1.6px 1.6px at 49% 20%,#ffe9a8,transparent),
     radial-gradient(1.6px 1.6px at 70% 12%,#fff,transparent),radial-gradient(1.6px 1.6px at 88% 28%,#9fe6da,transparent),
     radial-gradient(1.6px 1.6px at 24% 18%,#fff,transparent);}
  .edu-comet{position:absolute;top:14%;left:-15%;width:160px;height:2px;z-index:1;pointer-events:none;
     background:linear-gradient(90deg,transparent,#bfefff,#fff);border-radius:50%;opacity:0;
     box-shadow:0 0 8px #bfefff,0 0 24px rgba(150,210,255,.55);transform:rotate(15deg);
     animation:eduComet 13s linear infinite;}
  .edu-comet.edu-comet2{top:40%;animation-duration:17s;animation-delay:7s;}

  .edu-cine>*{position:relative;z-index:3;}

  /* nav superior */
  .edu-nav{display:flex;justify-content:space-between;align-items:center;gap:18px;flex-wrap:wrap;
     padding-bottom:8px;border-bottom:1px solid rgba(160,195,235,.12);}
  .edu-logo{font-family:'Archivo Black',sans-serif;font-size:18px;letter-spacing:.5px;color:#fff;}
  .edu-logo span{color:#7fd4ff;font-weight:400;font-family:'Archivo',sans-serif;font-size:13px;margin-left:6px;letter-spacing:1px;}
  .edu-nav nav{display:flex;gap:22px;flex-wrap:wrap;}
  .edu-nav nav a{font-size:12.5px;letter-spacing:.6px;color:#aebfd2;text-decoration:none;text-transform:uppercase;
     font-weight:600;transition:color .15s ease;}
  .edu-nav nav a:hover{color:#fff;}
  .edu-nav nav a.on{color:#7fd4ff;}

  /* etiquetas verticales decorativas (borde izquierdo) */
  .edu-vlabels{position:absolute;left:20px;top:54%;transform:translateY(-50%);z-index:3;
     display:flex;flex-direction:column;gap:30px;}
  .edu-vlabels span{writing-mode:vertical-rl;transform:rotate(180deg);font-size:10px;letter-spacing:3px;
     text-transform:uppercase;color:rgba(174,191,210,.6);font-weight:600;
     font-family:'Archivo Expanded','Archivo',sans-serif;}

  /* layout principal: titular gigante a todo el ancho */
  .edu-cine-grid{margin-top:30px;}
  .edu-kicker{display:inline-block;font-family:'Archivo Expanded','Archivo',sans-serif;font-size:10.5px;
     font-weight:700;letter-spacing:3px;text-transform:uppercase;color:#8fb4d8;margin-bottom:18px;
     padding-left:2px;animation:eduRise .8s cubic-bezier(.2,.7,.2,1) both;}

  .edu-mega{font-family:'Archivo Black',sans-serif;text-transform:uppercase;color:#f6faff;margin:0;
     font-size:clamp(44px,6.6vw,92px);line-height:.9;letter-spacing:-.01em;
     text-shadow:0 1px 0 #c4cfdd,0 2px 0 #aeb9c9,0 3px 0 #99a5b8,0 4px 0 #8593a8,0 5px 0 #74829a,
                 0 12px 22px rgba(0,0,0,.6);animation:eduRise .9s cubic-bezier(.2,.7,.2,1) both;}
  .edu-mega em{display:block;font-style:normal;color:#7fd4ff;
     text-shadow:0 0 30px rgba(127,212,255,.55),0 3px 0 rgba(10,40,70,.5);}

  .edu-lede{max-width:480px;margin:24px 0 0;color:#c4d3e4;font-size:16px;line-height:1.6;
     animation:eduRise .9s cubic-bezier(.2,.7,.2,1) .15s both;}

  .edu-cta{display:inline-flex;align-items:center;gap:12px;margin-top:26px;cursor:pointer;
     padding:14px 26px;border-radius:999px;text-decoration:none;font-weight:700;font-size:14.5px;
     letter-spacing:.4px;color:#06121f;background:linear-gradient(135deg,#aee1ff,#7fd4ff);
     box-shadow:0 14px 34px rgba(127,212,255,.35);transition:transform .18s ease,box-shadow .18s ease;
     animation:eduRise .9s cubic-bezier(.2,.7,.2,1) .3s both;}
  .edu-cta:hover{transform:translateY(-2px);box-shadow:0 18px 42px rgba(127,212,255,.5);}
  .edu-cta span{transition:transform .18s ease;} .edu-cta:hover span{transform:translateX(5px);}

  /* tarjetas glassmorphic en fila horizontal (hallazgos) bajo el titular */
  .edu-floats{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px;margin-top:40px;}
  .edu-glass{position:relative;display:flex;flex-direction:column;border-radius:18px;padding:22px 24px;color:#e9f1fb;
     background:linear-gradient(160deg,rgba(22,38,58,.55),rgba(10,18,30,.42));
     backdrop-filter:blur(14px) saturate(130%);-webkit-backdrop-filter:blur(14px) saturate(130%);
     border:1px solid rgba(160,200,240,.18);box-shadow:0 20px 50px rgba(0,0,0,.45),inset 0 1px 0 rgba(255,255,255,.08);
     transition:transform .2s ease,border-color .2s ease;animation:eduRise .9s cubic-bezier(.2,.7,.2,1) both;}
  .edu-floats .edu-glass:nth-child(1){animation-delay:.35s;}
  .edu-floats .edu-glass:nth-child(2){animation-delay:.46s;}
  .edu-floats .edu-glass:nth-child(3){animation-delay:.57s;}
  .edu-glass:hover{transform:translateY(-4px);border-color:rgba(127,212,255,.5);}
  .edu-glass h4{margin:0 0 8px;font-size:17px;font-weight:700;color:#fff;font-family:'Archivo Expanded','Archivo',sans-serif;}
  .edu-glass p{margin:0;font-size:13.5px;line-height:1.55;color:#b6c6d8;}
  .edu-glass-foot{display:flex;justify-content:space-between;align-items:center;margin-top:auto;padding-top:16px;gap:10px;}
  .edu-metric{font-size:12px;font-weight:700;color:#7fd4ff;letter-spacing:.3px;}
  .edu-glass-foot a{font-size:12.5px;font-weight:700;color:#fff;text-decoration:none;white-space:nowrap;
     border-bottom:1px solid rgba(127,212,255,.5);padding-bottom:1px;transition:color .15s ease;}
  .edu-glass-foot a:hover{color:#7fd4ff;}

  /* fila de fuentes (logos) */
  .edu-logos{display:flex;align-items:center;gap:26px;flex-wrap:wrap;margin-top:38px;padding-top:18px;
     border-top:1px solid rgba(160,195,235,.12);}
  .edu-logos-label{font-size:10px;letter-spacing:2.5px;text-transform:uppercase;color:#6f86a0;font-weight:700;}
  .edu-logos>span:not(.edu-logos-label){font-family:'Archivo Expanded','Archivo',sans-serif;font-weight:700;
     font-size:13px;letter-spacing:.5px;color:rgba(190,205,222,.55);transition:color .18s ease;}
  .edu-logos>span:not(.edu-logos-label):hover{color:#cfe0f2;}

  /* franja de metadatos académicos bajo el hero */
  .edu-metastrip{background:linear-gradient(180deg,#0a131f,#0b1422);padding:26px 52px 30px;
     border-top:1px solid rgba(160,195,235,.10);}
  .edu-meta{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:18px;}
  .edu-meta>div{display:flex;flex-direction:column;gap:4px;}
  .edu-meta .k{font-size:10px;letter-spacing:1.8px;text-transform:uppercase;color:#7fd4ff;font-weight:700;
     font-family:'Archivo Expanded','Archivo',sans-serif;}
  .edu-meta .v{font-size:13.5px;color:#cdd9e7;line-height:1.45;}
  .edu-disc{background:rgba(255,170,90,.09);border:1px solid rgba(255,185,120,.28);border-left:4px solid #ff9f5c;
     color:#ffd9b8;border-radius:14px;padding:14px 18px;font-size:12.8px;margin-top:22px;line-height:1.6;}
  .edu-disc b{color:#ffe9d2;}

  @media (max-width:820px){
     .edu-cine{padding:24px 30px 22px;min-height:auto;}
     .edu-floats{grid-template-columns:1fr;gap:14px;margin-top:30px;}
     .edu-vlabels{display:none;}
     .edu-nav nav{gap:14px;} .edu-sheet{padding:26px 22px 30px;}
  }

  /* ===================================================================
     ANIMACIONES
     =================================================================== */
  @keyframes eduBarFlow{0%{background-position:0% 0;}100%{background-position:220% 0;}}
  @keyframes eduPulse{0%,100%{box-shadow:0 0 0 rgba(127,212,255,0);}50%{box-shadow:0 0 16px rgba(127,212,255,.35);}}
  @keyframes eduHeroFlow{0%{background-position:0% 50%,0 0,0 0;}50%{background-position:100% 50%,0 0,0 0;}100%{background-position:0% 50%,0 0,0 0;}}
  @keyframes eduBreathe{0%,100%{box-shadow:0 40px 90px rgba(2,6,14,.6);}50%{box-shadow:0 46px 104px rgba(20,80,110,.5);}}
  @keyframes eduTwinkle{0%,100%{opacity:.35;}50%{opacity:1;}}
  @keyframes eduFog{0%,100%{opacity:.7;transform:translateX(0);}50%{opacity:1;transform:translateX(20px);}}
  @keyframes eduComet{0%{opacity:0;transform:translate(0,0) rotate(15deg);}5%{opacity:.95;}
     22%{opacity:0;transform:translate(1200px,330px) rotate(15deg);}100%{opacity:0;}}
  @keyframes eduRise{from{opacity:0;transform:translateY(20px);}to{opacity:1;transform:translateY(0);}}

  @media (prefers-reduced-motion:reduce){
     .edu-portada,.edu-cine,.edu-fog,.edu-stars,.edu-stars2,.edu-comet,.edu-sheet::before,.edu-eyebrow,
     .edu-kicker,.edu-mega,.edu-lede,.edu-cta,.edu-glass{animation:none!important;}
  }
</style><style>
.edu-banner{position:relative;overflow:hidden;border-radius:20px;margin:26px auto;max-width:1140px;
  padding:28px 42px;color:#e9f1fb;font-family:'Archivo',system-ui,sans-serif;line-height:1.62;font-size:15px;
  background:radial-gradient(72% 130% at 90% -25%,rgba(127,212,255,.16),transparent 60%),
             radial-gradient(80% 120% at 0% 132%,rgba(40,150,140,.14),transparent 60%),
             linear-gradient(168deg,#0c1a2b,#0a1626 58%,#060f1b);
  border:1px solid rgba(140,180,224,.16);box-shadow:0 30px 70px rgba(3,8,18,.5),inset 0 1px 0 rgba(255,255,255,.05);}
.edu-banner::before{content:"";position:absolute;top:0;left:0;right:0;height:4px;z-index:2;
  background:linear-gradient(90deg,#1d6fb0,#43c4b0 35%,#7fd4ff 55%,#43c4b0 75%,#1d6fb0);
  background-size:220% 100%;animation:eduBarFlow 7s linear infinite;}
.edu-banner>*{position:relative;z-index:1;}
.edu-banner .eb{display:inline-block;font-family:'Archivo Expanded','Archivo',sans-serif;font-size:10.5px;
  font-weight:700;letter-spacing:3px;text-transform:uppercase;color:#7fd4ff;
  background:rgba(127,212,255,.08);border:1px solid rgba(127,212,255,.30);padding:5px 15px;border-radius:999px;
  animation:eduPulse 3.4s ease-in-out infinite;}
.edu-banner h2{font-family:'Archivo Black',sans-serif;text-transform:uppercase;color:#f6faff;
  margin:15px 0 0;font-size:clamp(24px,3.2vw,38px);line-height:.96;letter-spacing:-.01em;
  text-shadow:0 2px 0 #8593a8,0 8px 18px rgba(0,0,0,.5);animation:eduRise .7s cubic-bezier(.2,.7,.2,1) both;}
.edu-banner h2 em{font-style:normal;color:#7fd4ff;text-shadow:0 0 26px rgba(127,212,255,.5);}
.edu-banner .lede{margin:14px 0 0;max-width:700px;color:#c4d3e4;font-size:15px;}
.edu-banner .step{position:absolute;right:34px;top:50%;transform:translateY(-50%);z-index:0;
  font-family:'Archivo Black',sans-serif;font-size:104px;line-height:1;color:rgba(127,212,255,.09);}
.edu-banner h3{font-family:'Archivo Expanded','Archivo',sans-serif;color:#7fd4ff;font-size:12px;
  letter-spacing:1.4px;text-transform:uppercase;margin:22px 0 6px;}
.edu-banner p{margin:8px 0;color:#cdd9e7;} .edu-banner b{color:#fff;}
.edu-banner ul{margin:10px 0 0;padding-left:2px;list-style:none;}
.edu-banner ul li{position:relative;padding-left:24px;margin:9px 0;color:#cdd9e7;}
.edu-banner ul li::before{content:"";position:absolute;left:3px;top:8px;width:8px;height:8px;border-radius:2px;
  background:linear-gradient(135deg,#7fd4ff,#43c4b0);transform:rotate(45deg);box-shadow:0 0 8px rgba(127,212,255,.5);}
.edu-banner .row{display:flex;gap:16px;margin:12px 0;padding:14px 18px;border-radius:13px;
  background:rgba(8,16,28,.5);border:1px solid rgba(140,180,224,.14);border-left:3px solid #43c4b0;}
.edu-banner .row.alt{border-left-color:#ff9f5c;}
.edu-banner .row .k{flex:0 0 132px;font:700 11px/1.5 'Archivo Expanded','Archivo',sans-serif;letter-spacing:1px;
  text-transform:uppercase;color:#ff9f5c;}
.edu-banner .row .v{flex:1;color:#dde7f2;font-size:14.5px;}
.edu-banner .foot{margin-top:22px;border-top:1px dashed rgba(140,180,224,.22);padding-top:13px;
  font-size:12.5px;color:#8295ab;}
@media (max-width:820px){.edu-banner{padding:22px 24px;} .edu-banner .step{display:none;}
  .edu-banner .row{flex-direction:column;gap:4px;} .edu-banner .row .k{flex:none;}}
</style><div style="filter:hue-rotate(330deg) saturate(1.0);"><div class="edu-portada">
  <div class="edu-cine">
     <div class="edu-fog"></div><div class="edu-stars"></div><div class="edu-stars2"></div>
     <span class="edu-comet"></span><span class="edu-comet edu-comet2"></span>
     <svg class="edu-ridge" viewBox="0 0 1200 200" preserveAspectRatio="none" aria-hidden="true">
        <defs><linearGradient id="eduRg" x1="0" y1="0" x2="0" y2="1">
        <stop offset="0" stop-color="#0d2034"/><stop offset="1" stop-color="#050b14"/></linearGradient></defs>
        <path d="M0,200 L0,118 L130,72 L250,112 L380,52 L520,118 L660,58 L800,116 L940,46 L1070,104 L1200,64 L1200,200 Z" fill="url(#eduRg)"/>
     </svg>
     <div class="edu-grain"></div>
     <header class="edu-nav"><div class="edu-logo">ds-colabs<span>· Data &amp; Machine Learning</span></div></header>
     <div class="edu-vlabels"><span>Taxi</span><span>Q-learning</span><span>Recompensa</span></div>
     <div class="edu-cine-grid"><div class="edu-cine-main">
        <span class="edu-kicker">Data &amp; Machine Learning · Reinforcement Learning (Q-learning tabular)</span>
        <h1 class="edu-mega">Q-learning en Taxi</h1>
        <p class="edu-lede">Un agente aprende a recoger y dejar pasajeros optimizando recompensa acumulada, sin modelo del entorno.</p>
        <a class="edu-cta" href="#">Explorar el análisis <span>&rarr;</span></a>
     </div>
     <aside class="edu-floats"><article class="edu-glass"><h4>Problema</h4><p>Taxi: 500 estados, 6 acciones. Recoger al pasajero y dejarlo en destino con el menor numero de pasos.</p><div class="edu-glass-foot"><span class="edu-metric">control</span><a>Ver análisis &rarr;</a></div></article><article class="edu-glass"><h4>Enfoque</h4><p>Q-learning tabular off-policy: actualizacion TD con regla de Bellman, exploracion epsilon-greedy que decae.</p><div class="edu-glass-foot"><span class="edu-metric">q-learning</span><a>Ver análisis &rarr;</a></div></article><article class="edu-glass"><h4>Metrica</h4><p>Recompensa media y pasos medios por episodio con politica greedy, contra un agente aleatorio.</p><div class="edu-glass-foot"><span class="edu-metric">reward</span><a>Ver análisis &rarr;</a></div></article></aside></div>
     <div class="edu-logos"><span class="edu-logos-label">Fuentes</span><span>Gymnasium</span><span>NumPy</span><span>pandas</span><span>Plotly</span></div>
  </div>
  <div class="edu-metastrip"><div class="edu-meta"><div><span class="k">Autor</span><span class="v">Nicolás Bargioni</span></div><div><span class="k">Rol</span><span class="v">Data Scientist</span></div><div><span class="k">Categoría</span><span class="v">Data &amp; Machine Learning</span></div><div><span class="k">Dataset</span><span class="v">No hay dataset; la experiencia se genera interactuando con el entorno</span></div></div></div>
</div></div>'''))

## 🧭 Marco del trabajo

| | |
|---|---|
| **Objetivo** | Entrenar un agente tabular que resuelva Taxi (recoger y dejar al pasajero por el camino corto) maximizando la recompensa acumulada, partiendo de cero conocimiento del entorno. |
| **Hipótesis** | Q-learning con epsilon-greedy y decay converge a una política casi óptima que supera ampliamente a un agente aleatorio, pasando de recompensa fuertemente negativa a recompensa positiva estable. |
| **Datos** | No hay dataset estático: el agente genera su propia experiencia (estado, acción, recompensa, siguiente estado) interactuando con el entorno Gymnasium a lo largo de miles de episodios. |
| **Metodología** | Entorno → tabla Q (500x6) inicializada en cero → entrenamiento por episodios con epsilon-greedy + decay de epsilon → política greedy → evaluación sobre 1000 episodios vs baseline aleatorio. |
| **Métrica** | Recompensa media y pasos medios por episodio (política greedy) |

> Ejecutable top-down · `random_state=42` · preprocesamiento **sin data leakage**.

## 🛠 0 · Setup

Imports y configuracion (Gymnasium + NumPy + Plotly). Semilla fija para reproducibilidad.

In [2]:
import warnings; warnings.filterwarnings('ignore')
import numpy as np, pandas as pd
import gymnasium as gym
import plotly.express as px, plotly.graph_objects as go, plotly.io as pio
pio.templates.default = 'plotly_dark'
SEED = 42
rng = np.random.default_rng(SEED)
PRIMARY, ACCENT = '#7fd4ff', '#ff9f5c'
print('Setup OK · gymnasium', gym.__version__, '· numpy', np.__version__)
print('Q-learning tabular sobre el entorno Taxi (Toy Text)')

Setup OK · gymnasium 1.3.0 · numpy 2.4.1
Q-learning tabular sobre el entorno Taxi (Toy Text)


## 🚕 1 · El entorno Taxi

Estados, acciones y como se codifica la situacion del taxi.

In [3]:
# El entorno Taxi: 500 estados discretos, 6 acciones discretas.
# (En gymnasium 1.x el id es 'Taxi-v4'; v3 quedo deprecado pero la dinamica es la misma.)
env = gym.make('Taxi-v4')
n_states  = env.observation_space.n
n_actions = env.action_space.n
print(f'Estados (observation_space): {n_states}')
print(f'Acciones (action_space):     {n_actions}')

# Decodificamos un estado para ver su estructura interna.
# El estado codifica: (fila_taxi, col_taxi, ubicacion_pasajero, destino)
obs, info = env.reset(seed=SEED)
taxi_row, taxi_col, pass_loc, dest = env.unwrapped.decode(obs)
print(f'\nEstado inicial = {obs}  ->  taxi=({taxi_row},{taxi_col}), '
      f'pasajero={pass_loc}, destino={dest}')
print('5 filas x 5 cols x 5 ubic.pasajero (4 paradas + dentro del taxi) x 4 destinos = 500')

# Las 6 acciones
acciones = {0:'Sur (abajo)', 1:'Norte (arriba)', 2:'Este (derecha)',
            3:'Oeste (izquierda)', 4:'Recoger pasajero', 5:'Dejar pasajero'}
print('\nAcciones:', acciones)

Estados (observation_space): 500
Acciones (action_space):     6

Estado inicial = 386  ->  taxi=(3,4), pasajero=1, destino=2
5 filas x 5 cols x 5 ubic.pasajero (4 paradas + dentro del taxi) x 4 destinos = 500

Acciones: {0: 'Sur (abajo)', 1: 'Norte (arriba)', 2: 'Este (derecha)', 3: 'Oeste (izquierda)', 4: 'Recoger pasajero', 5: 'Dejar pasajero'}


## 🎯 2 · Recompensas y baseline

El esquema de recompensas que guia el aprendizaje, y cuanto rinde no aprender (agente aleatorio).

In [4]:
# Esquema de recompensas del entorno (clave para entender que va a aprender el agente):
#   -1   por cada paso (penaliza demorar -> empuja al camino corto)
#  +20   por dejar al pasajero en el destino correcto (objetivo)
#  -10   por recoger/dejar de forma ilegal (penaliza la chapuza)
print('Recompensas:')
print('  -1   por paso             -> incentiva resolver rapido')
print('  +20  dropoff correcto     -> el objetivo del episodio')
print('  -10  pickup/dropoff ilegal-> castiga acciones invalidas')

# Cuanto rinde NO aprender: un agente aleatorio sobre 1000 episodios (baseline).
def correr_aleatorio(env, episodios=1000, max_pasos=200, seed=SEED):
    g = np.random.default_rng(seed)
    recs, pasos = [], []
    for ep in range(episodios):
        obs, _ = env.reset(seed=int(seed + ep))
        total, n = 0.0, 0
        for _ in range(max_pasos):
            a = int(g.integers(n_actions))
            obs, r, term, trunc, _ = env.step(a)
            total += r; n += 1
            if term or trunc:
                break
        recs.append(total); pasos.append(n)
    return np.array(recs), np.array(pasos)

rec_rand, pasos_rand = correr_aleatorio(env)
print(f'\nBASELINE (agente aleatorio, 1000 episodios):')
print(f'  recompensa media = {rec_rand.mean():.2f}')
print(f'  pasos medios     = {pasos_rand.mean():.1f}')

Recompensas:
  -1   por paso             -> incentiva resolver rapido
  +20  dropoff correcto     -> el objetivo del episodio
  -10  pickup/dropoff ilegal-> castiga acciones invalidas



BASELINE (agente aleatorio, 1000 episodios):
  recompensa media = -776.33
  pasos medios     = 197.3


**Por que Taxi es un buen banco de pruebas para RL tabular.** El espacio de estados es
**finito y chico** (500), asi que toda la funcion de valor cabe en una tabla `Q[estado, accion]`
de 500x6 = 3000 numeros. No hace falta una red neuronal: podemos guardar *un valor por cada
combinacion estado-accion* y actualizarlo directamente. Eso lo vuelve el ejemplo canonico para
entender la mecanica de Q-learning antes de saltar a Deep RL.

La recompensa esta diseñada para que **el comportamiento optimo emerja solo**: el `-1` por paso
empuja al camino corto, el `+20` premia cumplir el objetivo y el `-10` castiga las acciones
ilegales (intentar dejar al pasajero donde no corresponde). El agente no recibe ninguna
instruccion de *como* manejar; solo siente estas recompensas y tiene que descubrir la politica.

## 🧠 3 · Q-learning

Tabla Q de 500x6, entrenamiento por episodios con epsilon-greedy y decay de epsilon.

In [5]:
# ----------------------------------------------------------------------
# Q-LEARNING TABULAR
# Regla de actualizacion (Bellman, TD off-policy):
#   Q(s,a) <- Q(s,a) + alpha * [ r + gamma * max_a' Q(s',a')  -  Q(s,a) ]
#                              \_______________ TD target ______________/
# ----------------------------------------------------------------------
ALPHA      = 0.10     # tasa de aprendizaje: cuanto pesa cada nueva experiencia
GAMMA      = 0.99     # factor de descuento: cuanto valen las recompensas futuras
EPS_INI    = 1.0      # epsilon inicial: 100% exploracion al arrancar
EPS_FIN    = 0.01     # epsilon final: casi pura explotacion al final
EPS_DECAY  = 0.9995   # decay multiplicativo por episodio
EPISODIOS  = 20000
MAX_PASOS  = 200

Q = np.zeros((n_states, n_actions))     # tabla Q inicializada en cero
g = np.random.default_rng(SEED)         # RNG para la exploracion epsilon-greedy
eps = EPS_INI
recompensas_ep, pasos_ep, eps_ep = [], [], []

for ep in range(EPISODIOS):
    obs, _ = env.reset(seed=int(SEED + ep))
    total, n = 0.0, 0
    for _ in range(MAX_PASOS):
        # epsilon-greedy: con prob. eps exploro al azar, si no exploto el mejor Q
        if g.random() < eps:
            a = int(g.integers(n_actions))
        else:
            a = int(np.argmax(Q[obs]))
        nobs, r, term, trunc, _ = env.step(a)
        # actualizacion de Bellman
        td_target = r + GAMMA * np.max(Q[nobs]) * (not term)
        Q[obs, a] += ALPHA * (td_target - Q[obs, a])
        obs = nobs; total += r; n += 1
        if term or trunc:
            break
    recompensas_ep.append(total); pasos_ep.append(n); eps_ep.append(eps)
    eps = max(EPS_FIN, eps * EPS_DECAY)   # decay de epsilon

recompensas_ep = np.array(recompensas_ep)
pasos_ep = np.array(pasos_ep)
print(f'Entrenamiento terminado: {EPISODIOS} episodios')
print(f'epsilon final = {eps:.4f}  (arranco en {EPS_INI})')
print(f'recompensa media primeros 100 ep: {recompensas_ep[:100].mean():.1f}')
print(f'recompensa media ultimos  100 ep: {recompensas_ep[-100:].mean():.1f}')

Entrenamiento terminado: 20000 episodios
epsilon final = 0.0100  (arranco en 1.0)
recompensa media primeros 100 ep: -765.0
recompensa media ultimos  100 ep: 7.4


**Por que Q-learning.** Es el algoritmo *off-policy* mas directo para aprender control sin
modelo del entorno: no necesitamos conocer de antemano las probabilidades de transicion ni las
recompensas, solo *muestrearlas* actuando. La tabla `Q[s,a]` estima **cuanta recompensa futura
total esperamos** si en el estado `s` tomamos la accion `a` y despues jugamos optimo. Una vez
aprendida, la politica es trivial: en cada estado, elegir `argmax Q[s, ·]`.

**Que hace cada hiperparametro:**

- **alpha (0.10) — tasa de aprendizaje.** Cuanto corregimos `Q(s,a)` hacia la nueva evidencia en
  cada paso. Alta = aprende rapido pero inestable (ruido); baja = estable pero lento. 0.10 es un
  punto medio robusto para entornos deterministas como Taxi.
- **gamma (0.99) — factor de descuento.** Cuanto valen las recompensas futuras frente a la
  inmediata. Cerca de 1 (0.99) hace al agente **paciente**: prioriza el `+20` del final aunque
  cueste varios `-1` por el camino. Si fuera bajo, el agente seria miope y no "veria" la
  recompensa lejana del dropoff.
- **epsilon — tasa de exploracion.** Probabilidad de tomar una accion *al azar* en vez de la
  mejor conocida. Resuelve el dilema **explorar vs explotar**: si siempre explotara, se quedaria
  atrapado en lo primero que parezca bueno; si siempre explorara, nunca aprovecharia lo aprendido.

**El decay de epsilon es el mecanismo central.** Arrancamos en `eps=1.0` (100% exploracion: el
agente no sabe nada del mapa, conviene probar todo) y lo bajamos multiplicando por `0.9995` cada
episodio hasta un piso de `0.01`. La intuicion: **al principio explorar paga** (hay que conocer
el entorno), **al final explotar paga** (ya sabemos el camino, toca cobrarlo). El TD target usa
`max_a' Q(s',a')` —el *mejor* valor del siguiente estado, no la accion que efectivamente
tomamos— y por eso Q-learning es *off-policy*: aprende la politica optima incluso mientras se
comporta de forma exploratoria.

## 📈 4 · Curva de aprendizaje

Recompensa por episodio (media movil): la firma visual de que el agente esta aprendiendo.

In [6]:
# Curva de aprendizaje: recompensa por episodio con media movil (ventana 100).
# La media movil suaviza la varianza enorme episodio-a-episodio y deja ver la tendencia.
def media_movil(x, w=100):
    return pd.Series(x).rolling(w, min_periods=1).mean().values

mm_rec = media_movil(recompensas_ep, 100)
x = np.arange(EPISODIOS)

fig = go.Figure()
fig.add_trace(go.Scatter(x=x, y=recompensas_ep, mode='lines', name='recompensa cruda',
                         line=dict(color='rgba(127,212,255,0.18)', width=1)))
fig.add_trace(go.Scatter(x=x, y=mm_rec, mode='lines', name='media movil (100 ep)',
                         line=dict(color=PRIMARY, width=2.5)))
fig.add_hline(y=rec_rand.mean(), line_dash='dash', line_color=ACCENT,
              annotation_text=f'baseline aleatorio ({rec_rand.mean():.0f})',
              annotation_position='bottom right')
fig.update_layout(title='Curva de aprendizaje · recompensa por episodio (Q-learning)',
                  xaxis_title='Episodio', yaxis_title='Recompensa total del episodio',
                  legend=dict(orientation='h', y=-0.2))
fig.show()

# ¿En que episodio "converge"? Primer episodio cuya media movil supera +5 (umbral de exito)
umbral = 5.0
sup = np.where(mm_rec >= umbral)[0]
ep_conv = int(sup[0]) if len(sup) else None
print(f'Recompensa cruda: min={recompensas_ep.min():.0f}, max={recompensas_ep.max():.0f}')
print(f'Media movil final (ultimos 100 ep): {mm_rec[-1]:.2f}')
print(f'Converge (media movil cruza +{umbral:.0f}) en el episodio: {ep_conv}')

Recompensa cruda: min=-929, max=15
Media movil final (ultimos 100 ep): 7.39
Converge (media movil cruza +5) en el episodio: 5461


**Como leer la curva.** El trazo tenue es la recompensa cruda episodio-a-episodio: tiene una
varianza enorme porque cada episodio arranca en un estado aleatorio y, sobre todo al principio,
la exploracion mete acciones al azar. El trazo grueso es la **media movil de 100 episodios**, que
filtra ese ruido y deja ver la **tendencia real de aprendizaje**: la curva sube desde valores
fuertemente negativos (el agente choca, hace pickups ilegales, agota los pasos) hacia un plateau
positivo, donde ya resuelve casi siempre por el camino corto. La linea punteada marca el baseline
aleatorio: la distancia entre el plateau y esa linea es, literalmente, *cuanto vale haber
aprendido*.

## 🏁 5 · Evaluacion

Politica greedy sobre 1000 episodios vs baseline aleatorio: recompensa media y pasos medios.

In [7]:
# Evaluacion: politica GREEDY (epsilon=0, sin exploracion) sobre 1000 episodios.
def evaluar_greedy(env, Q, episodios=1000, max_pasos=200, seed=SEED):
    recs, pasos, exitos = [], [], 0
    for ep in range(episodios):
        obs, _ = env.reset(seed=int(seed + 10000 + ep))
        total, n = 0.0, 0
        for _ in range(max_pasos):
            a = int(np.argmax(Q[obs]))          # pura explotacion
            obs, r, term, trunc, _ = env.step(a)
            total += r; n += 1
            if term or trunc:
                if r == 20:                      # dropoff correcto
                    exitos += 1
                break
        recs.append(total); pasos.append(n)
    return np.array(recs), np.array(pasos), exitos

rec_greedy, pasos_greedy, exitos = evaluar_greedy(env, Q)

comp = pd.DataFrame({
    'Agente': ['Aleatorio (baseline)', 'Q-learning (greedy)'],
    'Recompensa media': [rec_rand.mean(), rec_greedy.mean()],
    'Pasos medios': [pasos_rand.mean(), pasos_greedy.mean()],
}).round(2)
print('COMPARACION sobre 1000 episodios de evaluacion:\n')
print(comp.to_string(index=False))
print(f'\nEpisodios resueltos con exito (dropoff correcto): {exitos}/1000 '
      f'= {100*exitos/1000:.1f}%')
print(f'Mejora de recompensa vs baseline: '
      f'{rec_greedy.mean() - rec_rand.mean():+.1f} puntos')

fig = px.bar(comp, x='Agente', y='Recompensa media', color='Agente', text='Recompensa media',
             color_discrete_map={'Aleatorio (baseline)': ACCENT, 'Q-learning (greedy)': PRIMARY},
             title='Recompensa media: Q-learning vs agente aleatorio (1000 episodios)')
fig.update_traces(textposition='outside'); fig.update_layout(showlegend=False)
fig.show()

COMPARACION sobre 1000 episodios de evaluacion:

              Agente  Recompensa media  Pasos medios
Aleatorio (baseline)           -776.33        197.34
 Q-learning (greedy)              7.89         13.11

Episodios resueltos con exito (dropoff correcto): 1000/1000 = 100.0%
Mejora de recompensa vs baseline: +784.2 puntos


**Por que evaluar con epsilon=0.** Durante el entrenamiento el agente explora (toma acciones
al azar de vez en cuando), lo cual ensucia la recompensa. Para medir *que tan buena es la politica
aprendida* apagamos la exploracion: en cada estado tomamos siempre `argmax Q[s, ·]`. Esa es la
**politica greedy**, la que de verdad usariamos en produccion. La comparamos contra el agente
aleatorio sobre el *mismo numero de episodios* (1000) para que el contraste sea justo: misma vara,
dos politicas.

### 📌 Lectura de resultados

Tras **20.000 episodios** de entrenamiento (con `alpha=0.10`, `gamma=0.99` y epsilon
decayendo de `1.0` a `0.01`), evaluamos la politica greedy sobre **1.000 episodios** y la
comparamos contra el agente aleatorio en la misma cantidad de episodios:

| Agente | Recompensa media | Pasos medios | Exito |
|---|---|---|---|
| Aleatorio (baseline) | **-776.33** | 197.3 | ~0% |
| Q-learning (greedy) | **+7.89** | **13.1** | **1000/1000 (100%)** |

**Que dicen los numeros:**

- **La recompensa salta de -776.33 a +7.89: una mejora de +784 puntos.** El baseline aleatorio
  practicamente nunca resuelve el episodio; acumula cientos de penalizaciones (`-1` por paso
  durante los 197 pasos hasta agotar el limite, mas `-10` por cada pickup/dropoff ilegal). El
  agente entrenado, en cambio, va directo: **resuelve los 1000 episodios** (100% de dropoffs
  correctos) en apenas **13 pasos de media**.

- **Por que +7.89 y no mas:** el optimo teorico de Taxi ronda recompensa media ~8, porque cada
  episodio paga inevitablemente unos cuantos `-1` por los pasos minimos necesarios antes de
  cobrar el `+20`. Estar en ~7.9 con dropoff correcto en el 100% de los casos indica que el
  agente aprendio **casi la politica optima**: no malgasta pasos ni comete acciones ilegales.

- **Los pasos caen de 197.3 a 13.1** (15x menos): la metrica mas tangible de que el agente
  encontro el camino corto. El `-1` por paso hizo su trabajo: penalizar la demora empujo a la
  politica hacia trayectorias eficientes.

**La curva confirma el aprendizaje.** La media movil arranca cerca de **-765** (primeros 100
episodios, casi todo exploracion al azar) y termina en **+7.39** (ultimos 100 episodios). El
cruce del umbral de exito (+5) ocurre alrededor del **episodio 5.461**: ese es el punto donde el
agente deja de penar y empieza a resolver con consistencia. El resto del entrenamiento afina la
politica y, con el epsilon ya bajo, la explota.

**Conexion con la hipotesis.** Se valida por completo: Q-learning con epsilon-greedy y decay
**convergio a una politica casi optima** que supera al agente aleatorio por +784 puntos, pasando
de recompensa fuertemente negativa a positiva estable. Y lo logro **sin ningun modelo previo del
entorno**: solo prueba, error y la regla de actualizacion de Bellman.

## ✅ Conclusiones

- Q-learning **aprende sin modelo del entorno**: solo prueba, error y la regla de actualizacion de Bellman bastan para hallar una politica casi optima.
- El **decay de epsilon** es el corazon del balance explorar/explotar: mucha exploracion al principio (conocer el mapa), casi pura explotacion al final (cobrar lo aprendido).
- La **curva de aprendizaje** muestra la transicion de recompensa fuertemente negativa a positiva estable: es la firma visual de que el agente dejo de penar.
- Proximos pasos: epsilon-decay exponencial, comparar contra SARSA (on-policy) y dar el salto a Deep Q-Network cuando el espacio de estados es demasiado grande para una tabla.

---
*Nicolás Bargioni · Data Scientist · [nicolasbargioni.com](https://nicolasbargioni.com)*