# Regresión sobre California Housing
*BigQuery · Cloud & Deploy*

In [1]:
#@title 📌 Portada
from IPython.display import HTML, display
display(HTML(r'''<style>
  @import url('https://fonts.googleapis.com/css2?family=Archivo+Black&family=Archivo:wght@400;500;600;700&family=Archivo+Expanded:wght@600;700;800&display=swap');

  /* ===================================================================
     SISTEMA EDITORIAL CINEMATOGRÁFICO OSCURO
     Paleta fría documental · tipografía display extruida · vidrio esmerilado
     =================================================================== */

  /* ---------- contenedor base ---------- */
  .edu{max-width:1140px;margin:24px auto;font-family:'Archivo',system-ui,sans-serif;
       color:#dde7f2;line-height:1.66;font-size:15px;}
  .edu *{box-sizing:border-box;}

  /* ---------- hoja: panel de vidrio oscuro ---------- */
  .edu-sheet{position:relative;overflow:hidden;border-radius:22px;padding:36px 44px 40px;
     color:#e6eef8;background:linear-gradient(168deg,rgba(17,30,47,.94),rgba(9,16,27,.96));
     border:1px solid rgba(140,180,224,.14);
     box-shadow:0 30px 70px rgba(3,8,18,.55),inset 0 1px 0 rgba(255,255,255,.05);}
  .edu-sheet::before{content:"";position:absolute;top:0;left:0;right:0;height:4px;
     background:linear-gradient(90deg,#1d6fb0,#43c4b0 35%,#7fd4ff 55%,#43c4b0 75%,#1d6fb0);
     background-size:220% 100%;animation:eduBarFlow 7s linear infinite;}
  .edu-sheet::after{content:"";position:absolute;inset:0;pointer-events:none;z-index:0;opacity:.5;
     background:radial-gradient(110% 60% at 88% -10%,rgba(127,212,255,.10),transparent 60%);}
  .edu-sheet>*{position:relative;z-index:1;}

  /* ---------- eyebrow / etiqueta ---------- */
  .edu-eyebrow{display:inline-block;font-family:'Archivo Expanded','Archivo',sans-serif;
     font-size:10.5px;font-weight:700;letter-spacing:3px;text-transform:uppercase;color:#7fd4ff;
     background:rgba(127,212,255,.08);border:1px solid rgba(127,212,255,.30);
     padding:6px 16px;border-radius:999px;margin-bottom:18px;animation:eduPulse 3.4s ease-in-out infinite;}

  /* ---------- títulos ---------- */
  .edu h2{font-family:'Archivo Expanded','Archivo',sans-serif;color:#f1f7ff;font-size:23px;
     font-weight:800;letter-spacing:.3px;text-transform:uppercase;margin:34px 0 14px;
     padding:6px 0 10px 18px;border-left:4px solid #43c4b0;
     background:linear-gradient(90deg,rgba(67,196,176,.12),transparent 60%);}
  .edu h2:first-child{margin-top:0;}
  .edu h2.alt{border-left-color:#ff8f6b;background:linear-gradient(90deg,rgba(255,143,107,.13),transparent 60%);}
  .edu h3{color:#7fd4ff;font-size:12px;font-weight:700;letter-spacing:1.4px;
     text-transform:uppercase;margin:22px 0 6px;font-family:'Archivo Expanded','Archivo',sans-serif;}
  .edu p{margin:9px 0;color:#cdd9e7;}
  .edu b,.edu strong{color:#ffffff;font-weight:700;}
  .edu i,.edu em{color:#bfe6ff;}
  .edu code{background:rgba(127,212,255,.12);border:1px solid rgba(127,212,255,.26);border-radius:5px;
     padding:1px 7px;font-size:13px;color:#bfe6ff;font-family:ui-monospace,Menlo,monospace;}

  /* ---------- listas con viñeta propia ---------- */
  .edu ul{margin:6px 0;padding-left:2px;list-style:none;}
  .edu ul li{position:relative;padding-left:26px;margin:8px 0;color:#cdd9e7;}
  .edu ul li::before{content:"";position:absolute;left:4px;top:9px;width:8px;height:8px;border-radius:2px;
     background:linear-gradient(135deg,#7fd4ff,#43c4b0);transform:rotate(45deg);box-shadow:0 0 8px rgba(127,212,255,.5);}

  /* ---------- tablas ---------- */
  .edu-tbl{border-collapse:separate;border-spacing:0;width:100%;font-size:14px;margin:16px 0;
     border:1px solid rgba(140,180,224,.16);border-radius:14px;overflow:hidden;
     background:rgba(8,15,26,.45);box-shadow:0 10px 30px rgba(3,8,18,.4);}
  .edu-tbl th{background:linear-gradient(135deg,#103a5e,#1c6aa6);color:#eaf4ff;font-weight:700;
     padding:12px 15px;text-align:left;letter-spacing:.4px;border:none;
     font-family:'Archivo Expanded','Archivo',sans-serif;font-size:12px;text-transform:uppercase;}
  .edu-tbl td{padding:10px 15px;border:none;border-top:1px solid rgba(140,180,224,.10);color:#d4e0ee;}
  .edu-tbl tr:nth-child(even) td{background:rgba(255,255,255,.025);}
  .edu-tbl tr:hover td{background:rgba(127,212,255,.10);}
  .edu-tbl .num,.edu-tbl td.num{text-align:right;font-variant-numeric:tabular-nums;}

  /* ---------- grid de tarjetas ---------- */
  .edu-grid{display:flex;flex-wrap:wrap;gap:16px;margin:16px 0;}
  .edu-card{flex:1 1 220px;border-radius:16px;padding:18px 20px;
     background:linear-gradient(160deg,rgba(24,40,60,.6),rgba(13,23,37,.5));
     border:1px solid rgba(140,180,224,.16);transition:transform .18s ease,box-shadow .18s ease,border-color .18s ease;}
  .edu-card:hover{transform:translateY(-4px);box-shadow:0 16px 34px rgba(3,8,18,.5);border-color:rgba(127,212,255,.4);}
  .edu-card h3{margin:0 0 6px;}
  .edu-card p{margin:0;font-size:14px;color:#aebfd2;line-height:1.5;}

  /* ---------- KPIs / cifras ---------- */
  .edu-kpis{display:flex;flex-wrap:wrap;gap:14px;margin:18px 0;}
  .edu-kpi{flex:1 1 150px;text-align:center;border-radius:16px;padding:18px 14px;
     background:linear-gradient(165deg,rgba(20,38,58,.7),rgba(10,18,30,.6));
     border:1px solid rgba(140,180,224,.18);box-shadow:inset 0 1px 0 rgba(255,255,255,.05);}
  .edu-kpi .v{font-size:30px;font-weight:800;color:#7fd4ff;line-height:1;
     font-family:'Archivo Expanded','Archivo',sans-serif;text-shadow:0 0 22px rgba(127,212,255,.4);}
  .edu-kpi .l{font-size:10.5px;text-transform:uppercase;letter-spacing:1.2px;color:#8ea3ba;margin-top:8px;}

  /* ---------- callouts ---------- */
  .edu-note,.edu-warn,.edu-ok{border-radius:14px;padding:15px 20px;margin:16px 0;font-size:14px;
     line-height:1.62;border:1px solid;border-left-width:4px;backdrop-filter:blur(4px);}
  .edu-note{background:rgba(47,159,224,.10);border-color:rgba(127,212,255,.26);border-left-color:#7fd4ff;color:#cfe7fb;}
  .edu-warn{background:rgba(255,160,90,.10);border-color:rgba(255,180,110,.30);border-left-color:#ff9f5c;color:#ffd9b8;}
  .edu-ok{background:rgba(67,196,176,.10);border-color:rgba(90,220,190,.30);border-left-color:#43c4b0;color:#bff0e4;}
  .edu-note b,.edu-warn b,.edu-ok b{color:#fff;}

  /* ---------- spans destacados ---------- */
  .edu .hl{color:#7fd4ff;font-weight:700;} .edu .ok{color:#5ce0b5;font-weight:700;}
  .edu .warn{color:#ff9f5c;font-weight:700;}

  /* ---------- caption / pie ---------- */
  .edu-cap{font-size:12.5px;color:#8295ab;margin-top:12px;}
  .edu-foot{font-size:12.5px;color:#8295ab;margin-top:22px;border-top:1px dashed rgba(140,180,224,.22);padding-top:14px;}

  /* ---------- referencias ---------- */
  .edu-ref{background:rgba(8,16,28,.5);border:1px solid rgba(140,180,224,.16);border-left:4px solid #7fd4ff;
     border-radius:12px;padding:18px 20px;font-size:13.5px;color:#b9c8da;line-height:1.75;}

  /* ===================================================================
     PORTADA · HERO CINEMATOGRÁFICO
     =================================================================== */
  .edu-portada{max-width:1180px;margin:26px auto;border-radius:26px;overflow:hidden;
     font-family:'Archivo',system-ui,sans-serif;color:#e9f1fb;border:1px solid rgba(120,160,210,.18);
     box-shadow:0 40px 90px rgba(2,6,14,.6);animation:eduBreathe 12s ease-in-out infinite;}

  .edu-cine{position:relative;overflow:hidden;padding:26px 52px 24px 78px;min-height:560px;
     background:
        radial-gradient(60% 42% at 78% 6%,rgba(170,210,255,.20),transparent 55%),
        radial-gradient(80% 60% at 6% 104%,rgba(40,150,140,.20),transparent 60%),
        linear-gradient(180deg,#0c1a2b 0%,#0a1626 42%,#060f1b 100%);
     background-size:130% 130%,100% 100%,100% 100%;animation:eduHeroFlow 20s ease infinite;}

  /* atmósfera: niebla, grano, montañas, estrellas, cometas (todo CSS, sin imágenes externas) */
  .edu-fog{position:absolute;inset:0;z-index:0;pointer-events:none;
     background:radial-gradient(50% 38% at 50% 26%,rgba(150,190,230,.16),transparent 72%);filter:blur(14px);
     animation:eduFog 16s ease-in-out infinite;}
  .edu-grain{position:absolute;inset:0;z-index:2;pointer-events:none;opacity:.32;mix-blend-mode:overlay;
     background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='120' height='120'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='2' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E");}
  .edu-ridge{position:absolute;left:0;right:0;bottom:0;width:100%;height:190px;z-index:1;pointer-events:none;display:block;}
  .edu-stars,.edu-stars2{position:absolute;inset:0;pointer-events:none;z-index:1;}
  .edu-stars{animation:eduTwinkle 4.5s ease-in-out infinite;background-image:
     radial-gradient(1px 1px at 12% 22%,#fff,transparent),radial-gradient(1px 1px at 28% 64%,#fff,transparent),
     radial-gradient(1px 1px at 44% 14%,#fff,transparent),radial-gradient(1px 1px at 63% 38%,#fff,transparent),
     radial-gradient(1px 1px at 82% 33%,#fff,transparent),radial-gradient(1px 1px at 91% 20%,#fff,transparent),
     radial-gradient(1px 1px at 7% 48%,#fff,transparent),radial-gradient(1px 1px at 35% 12%,#fff,transparent);}
  .edu-stars2{animation:eduTwinkle 7s ease-in-out infinite;animation-delay:1.6s;background-image:
     radial-gradient(1.6px 1.6px at 18% 30%,#bfefff,transparent),radial-gradient(1.6px 1.6px at 49% 20%,#ffe9a8,transparent),
     radial-gradient(1.6px 1.6px at 70% 12%,#fff,transparent),radial-gradient(1.6px 1.6px at 88% 28%,#9fe6da,transparent),
     radial-gradient(1.6px 1.6px at 24% 18%,#fff,transparent);}
  .edu-comet{position:absolute;top:14%;left:-15%;width:160px;height:2px;z-index:1;pointer-events:none;
     background:linear-gradient(90deg,transparent,#bfefff,#fff);border-radius:50%;opacity:0;
     box-shadow:0 0 8px #bfefff,0 0 24px rgba(150,210,255,.55);transform:rotate(15deg);
     animation:eduComet 13s linear infinite;}
  .edu-comet.edu-comet2{top:40%;animation-duration:17s;animation-delay:7s;}

  .edu-cine>*{position:relative;z-index:3;}

  /* nav superior */
  .edu-nav{display:flex;justify-content:space-between;align-items:center;gap:18px;flex-wrap:wrap;
     padding-bottom:8px;border-bottom:1px solid rgba(160,195,235,.12);}
  .edu-logo{font-family:'Archivo Black',sans-serif;font-size:18px;letter-spacing:.5px;color:#fff;}
  .edu-logo span{color:#7fd4ff;font-weight:400;font-family:'Archivo',sans-serif;font-size:13px;margin-left:6px;letter-spacing:1px;}
  .edu-nav nav{display:flex;gap:22px;flex-wrap:wrap;}
  .edu-nav nav a{font-size:12.5px;letter-spacing:.6px;color:#aebfd2;text-decoration:none;text-transform:uppercase;
     font-weight:600;transition:color .15s ease;}
  .edu-nav nav a:hover{color:#fff;}
  .edu-nav nav a.on{color:#7fd4ff;}

  /* etiquetas verticales decorativas (borde izquierdo) */
  .edu-vlabels{position:absolute;left:20px;top:54%;transform:translateY(-50%);z-index:3;
     display:flex;flex-direction:column;gap:30px;}
  .edu-vlabels span{writing-mode:vertical-rl;transform:rotate(180deg);font-size:10px;letter-spacing:3px;
     text-transform:uppercase;color:rgba(174,191,210,.6);font-weight:600;
     font-family:'Archivo Expanded','Archivo',sans-serif;}

  /* layout principal: titular gigante a todo el ancho */
  .edu-cine-grid{margin-top:30px;}
  .edu-kicker{display:inline-block;font-family:'Archivo Expanded','Archivo',sans-serif;font-size:10.5px;
     font-weight:700;letter-spacing:3px;text-transform:uppercase;color:#8fb4d8;margin-bottom:18px;
     padding-left:2px;animation:eduRise .8s cubic-bezier(.2,.7,.2,1) both;}

  .edu-mega{font-family:'Archivo Black',sans-serif;text-transform:uppercase;color:#f6faff;margin:0;
     font-size:clamp(44px,6.6vw,92px);line-height:.9;letter-spacing:-.01em;
     text-shadow:0 1px 0 #c4cfdd,0 2px 0 #aeb9c9,0 3px 0 #99a5b8,0 4px 0 #8593a8,0 5px 0 #74829a,
                 0 12px 22px rgba(0,0,0,.6);animation:eduRise .9s cubic-bezier(.2,.7,.2,1) both;}
  .edu-mega em{display:block;font-style:normal;color:#7fd4ff;
     text-shadow:0 0 30px rgba(127,212,255,.55),0 3px 0 rgba(10,40,70,.5);}

  .edu-lede{max-width:480px;margin:24px 0 0;color:#c4d3e4;font-size:16px;line-height:1.6;
     animation:eduRise .9s cubic-bezier(.2,.7,.2,1) .15s both;}

  .edu-cta{display:inline-flex;align-items:center;gap:12px;margin-top:26px;cursor:pointer;
     padding:14px 26px;border-radius:999px;text-decoration:none;font-weight:700;font-size:14.5px;
     letter-spacing:.4px;color:#06121f;background:linear-gradient(135deg,#aee1ff,#7fd4ff);
     box-shadow:0 14px 34px rgba(127,212,255,.35);transition:transform .18s ease,box-shadow .18s ease;
     animation:eduRise .9s cubic-bezier(.2,.7,.2,1) .3s both;}
  .edu-cta:hover{transform:translateY(-2px);box-shadow:0 18px 42px rgba(127,212,255,.5);}
  .edu-cta span{transition:transform .18s ease;} .edu-cta:hover span{transform:translateX(5px);}

  /* tarjetas glassmorphic en fila horizontal (hallazgos) bajo el titular */
  .edu-floats{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px;margin-top:40px;}
  .edu-glass{position:relative;display:flex;flex-direction:column;border-radius:18px;padding:22px 24px;color:#e9f1fb;
     background:linear-gradient(160deg,rgba(22,38,58,.55),rgba(10,18,30,.42));
     backdrop-filter:blur(14px) saturate(130%);-webkit-backdrop-filter:blur(14px) saturate(130%);
     border:1px solid rgba(160,200,240,.18);box-shadow:0 20px 50px rgba(0,0,0,.45),inset 0 1px 0 rgba(255,255,255,.08);
     transition:transform .2s ease,border-color .2s ease;animation:eduRise .9s cubic-bezier(.2,.7,.2,1) both;}
  .edu-floats .edu-glass:nth-child(1){animation-delay:.35s;}
  .edu-floats .edu-glass:nth-child(2){animation-delay:.46s;}
  .edu-floats .edu-glass:nth-child(3){animation-delay:.57s;}
  .edu-glass:hover{transform:translateY(-4px);border-color:rgba(127,212,255,.5);}
  .edu-glass h4{margin:0 0 8px;font-size:17px;font-weight:700;color:#fff;font-family:'Archivo Expanded','Archivo',sans-serif;}
  .edu-glass p{margin:0;font-size:13.5px;line-height:1.55;color:#b6c6d8;}
  .edu-glass-foot{display:flex;justify-content:space-between;align-items:center;margin-top:auto;padding-top:16px;gap:10px;}
  .edu-metric{font-size:12px;font-weight:700;color:#7fd4ff;letter-spacing:.3px;}
  .edu-glass-foot a{font-size:12.5px;font-weight:700;color:#fff;text-decoration:none;white-space:nowrap;
     border-bottom:1px solid rgba(127,212,255,.5);padding-bottom:1px;transition:color .15s ease;}
  .edu-glass-foot a:hover{color:#7fd4ff;}

  /* fila de fuentes (logos) */
  .edu-logos{display:flex;align-items:center;gap:26px;flex-wrap:wrap;margin-top:38px;padding-top:18px;
     border-top:1px solid rgba(160,195,235,.12);}
  .edu-logos-label{font-size:10px;letter-spacing:2.5px;text-transform:uppercase;color:#6f86a0;font-weight:700;}
  .edu-logos>span:not(.edu-logos-label){font-family:'Archivo Expanded','Archivo',sans-serif;font-weight:700;
     font-size:13px;letter-spacing:.5px;color:rgba(190,205,222,.55);transition:color .18s ease;}
  .edu-logos>span:not(.edu-logos-label):hover{color:#cfe0f2;}

  /* franja de metadatos académicos bajo el hero */
  .edu-metastrip{background:linear-gradient(180deg,#0a131f,#0b1422);padding:26px 52px 30px;
     border-top:1px solid rgba(160,195,235,.10);}
  .edu-meta{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:18px;}
  .edu-meta>div{display:flex;flex-direction:column;gap:4px;}
  .edu-meta .k{font-size:10px;letter-spacing:1.8px;text-transform:uppercase;color:#7fd4ff;font-weight:700;
     font-family:'Archivo Expanded','Archivo',sans-serif;}
  .edu-meta .v{font-size:13.5px;color:#cdd9e7;line-height:1.45;}
  .edu-disc{background:rgba(255,170,90,.09);border:1px solid rgba(255,185,120,.28);border-left:4px solid #ff9f5c;
     color:#ffd9b8;border-radius:14px;padding:14px 18px;font-size:12.8px;margin-top:22px;line-height:1.6;}
  .edu-disc b{color:#ffe9d2;}

  @media (max-width:820px){
     .edu-cine{padding:24px 30px 22px;min-height:auto;}
     .edu-floats{grid-template-columns:1fr;gap:14px;margin-top:30px;}
     .edu-vlabels{display:none;}
     .edu-nav nav{gap:14px;} .edu-sheet{padding:26px 22px 30px;}
  }

  /* ===================================================================
     ANIMACIONES
     =================================================================== */
  @keyframes eduBarFlow{0%{background-position:0% 0;}100%{background-position:220% 0;}}
  @keyframes eduPulse{0%,100%{box-shadow:0 0 0 rgba(127,212,255,0);}50%{box-shadow:0 0 16px rgba(127,212,255,.35);}}
  @keyframes eduHeroFlow{0%{background-position:0% 50%,0 0,0 0;}50%{background-position:100% 50%,0 0,0 0;}100%{background-position:0% 50%,0 0,0 0;}}
  @keyframes eduBreathe{0%,100%{box-shadow:0 40px 90px rgba(2,6,14,.6);}50%{box-shadow:0 46px 104px rgba(20,80,110,.5);}}
  @keyframes eduTwinkle{0%,100%{opacity:.35;}50%{opacity:1;}}
  @keyframes eduFog{0%,100%{opacity:.7;transform:translateX(0);}50%{opacity:1;transform:translateX(20px);}}
  @keyframes eduComet{0%{opacity:0;transform:translate(0,0) rotate(15deg);}5%{opacity:.95;}
     22%{opacity:0;transform:translate(1200px,330px) rotate(15deg);}100%{opacity:0;}}
  @keyframes eduRise{from{opacity:0;transform:translateY(20px);}to{opacity:1;transform:translateY(0);}}

  @media (prefers-reduced-motion:reduce){
     .edu-portada,.edu-cine,.edu-fog,.edu-stars,.edu-stars2,.edu-comet,.edu-sheet::before,.edu-eyebrow,
     .edu-kicker,.edu-mega,.edu-lede,.edu-cta,.edu-glass{animation:none!important;}
  }
</style><style>
.edu-banner{position:relative;overflow:hidden;border-radius:20px;margin:26px auto;max-width:1140px;
  padding:28px 42px;color:#e9f1fb;font-family:'Archivo',system-ui,sans-serif;line-height:1.62;font-size:15px;
  background:radial-gradient(72% 130% at 90% -25%,rgba(127,212,255,.16),transparent 60%),
             radial-gradient(80% 120% at 0% 132%,rgba(40,150,140,.14),transparent 60%),
             linear-gradient(168deg,#0c1a2b,#0a1626 58%,#060f1b);
  border:1px solid rgba(140,180,224,.16);box-shadow:0 30px 70px rgba(3,8,18,.5),inset 0 1px 0 rgba(255,255,255,.05);}
.edu-banner::before{content:"";position:absolute;top:0;left:0;right:0;height:4px;z-index:2;
  background:linear-gradient(90deg,#1d6fb0,#43c4b0 35%,#7fd4ff 55%,#43c4b0 75%,#1d6fb0);
  background-size:220% 100%;animation:eduBarFlow 7s linear infinite;}
.edu-banner>*{position:relative;z-index:1;}
.edu-banner .eb{display:inline-block;font-family:'Archivo Expanded','Archivo',sans-serif;font-size:10.5px;
  font-weight:700;letter-spacing:3px;text-transform:uppercase;color:#7fd4ff;
  background:rgba(127,212,255,.08);border:1px solid rgba(127,212,255,.30);padding:5px 15px;border-radius:999px;
  animation:eduPulse 3.4s ease-in-out infinite;}
.edu-banner h2{font-family:'Archivo Black',sans-serif;text-transform:uppercase;color:#f6faff;
  margin:15px 0 0;font-size:clamp(24px,3.2vw,38px);line-height:.96;letter-spacing:-.01em;
  text-shadow:0 2px 0 #8593a8,0 8px 18px rgba(0,0,0,.5);animation:eduRise .7s cubic-bezier(.2,.7,.2,1) both;}
.edu-banner h2 em{font-style:normal;color:#7fd4ff;text-shadow:0 0 26px rgba(127,212,255,.5);}
.edu-banner .lede{margin:14px 0 0;max-width:700px;color:#c4d3e4;font-size:15px;}
.edu-banner .step{position:absolute;right:34px;top:50%;transform:translateY(-50%);z-index:0;
  font-family:'Archivo Black',sans-serif;font-size:104px;line-height:1;color:rgba(127,212,255,.09);}
.edu-banner h3{font-family:'Archivo Expanded','Archivo',sans-serif;color:#7fd4ff;font-size:12px;
  letter-spacing:1.4px;text-transform:uppercase;margin:22px 0 6px;}
.edu-banner p{margin:8px 0;color:#cdd9e7;} .edu-banner b{color:#fff;}
.edu-banner ul{margin:10px 0 0;padding-left:2px;list-style:none;}
.edu-banner ul li{position:relative;padding-left:24px;margin:9px 0;color:#cdd9e7;}
.edu-banner ul li::before{content:"";position:absolute;left:3px;top:8px;width:8px;height:8px;border-radius:2px;
  background:linear-gradient(135deg,#7fd4ff,#43c4b0);transform:rotate(45deg);box-shadow:0 0 8px rgba(127,212,255,.5);}
.edu-banner .row{display:flex;gap:16px;margin:12px 0;padding:14px 18px;border-radius:13px;
  background:rgba(8,16,28,.5);border:1px solid rgba(140,180,224,.14);border-left:3px solid #43c4b0;}
.edu-banner .row.alt{border-left-color:#ff9f5c;}
.edu-banner .row .k{flex:0 0 132px;font:700 11px/1.5 'Archivo Expanded','Archivo',sans-serif;letter-spacing:1px;
  text-transform:uppercase;color:#ff9f5c;}
.edu-banner .row .v{flex:1;color:#dde7f2;font-size:14.5px;}
.edu-banner .foot{margin-top:22px;border-top:1px dashed rgba(140,180,224,.22);padding-top:13px;
  font-size:12.5px;color:#8295ab;}
@media (max-width:820px){.edu-banner{padding:22px 24px;} .edu-banner .step{display:none;}
  .edu-banner .row{flex-direction:column;gap:4px;} .edu-banner .row .k{flex:none;}}
</style><div style="filter:hue-rotate(62deg) saturate(1.0);"><div class="edu-portada">
  <div class="edu-cine">
     <div class="edu-fog"></div><div class="edu-stars"></div><div class="edu-stars2"></div>
     <span class="edu-comet"></span><span class="edu-comet edu-comet2"></span>
     <svg class="edu-ridge" viewBox="0 0 1200 200" preserveAspectRatio="none" aria-hidden="true">
        <defs><linearGradient id="eduRg" x1="0" y1="0" x2="0" y2="1">
        <stop offset="0" stop-color="#0d2034"/><stop offset="1" stop-color="#050b14"/></linearGradient></defs>
        <path d="M0,200 L0,118 L130,72 L250,112 L380,52 L520,118 L660,58 L800,116 L940,46 L1070,104 L1200,64 L1200,200 Z" fill="url(#eduRg)"/>
     </svg>
     <div class="edu-grain"></div>
     <header class="edu-nav"><div class="edu-logo">ds-colabs<span>· Cloud &amp; Deploy</span></div></header>
     <div class="edu-vlabels"><span>scikit-learn</span><span>Regresion</span><span>R²</span></div>
     <div class="edu-cine-grid"><div class="edu-cine-main">
        <span class="edu-kicker">Cloud &amp; Deploy · BigQuery</span>
        <h1 class="edu-mega">Regresión sobre California Housing</h1>
        <p class="edu-lede">Regresión supervisada: del EDA al modelo, evaluando el error fuera de muestra.</p>
        <a class="edu-cta" href="#">Explorar el análisis <span>&rarr;</span></a>
     </div>
     <aside class="edu-floats"><article class="edu-glass"><h4>Datos</h4><p>20640 bloques censales; ingreso, ocupación, ubicación → valor medio de vivienda.</p><div class="edu-glass-foot"><span class="edu-metric">scikit-learn</span><a>Ver análisis &rarr;</a></div></article><article class="edu-glass"><h4>Enfoque</h4><p>Regresión supervisada: del EDA al modelo, evaluando el error fuera de muestra.</p><div class="edu-glass-foot"><span class="edu-metric">LinearReg vs. RandomForest</span><a>Ver análisis &rarr;</a></div></article><article class="edu-glass"><h4>Métrica</h4><p>Se evalúa con R² / RMSE.</p><div class="edu-glass-foot"><span class="edu-metric">Rigor</span><a>Ver análisis &rarr;</a></div></article></aside></div>
     <div class="edu-logos"><span class="edu-logos-label">Fuentes</span><span>Kaggle</span><span>Hugging Face</span><span>scikit-learn</span><span>Google Colab</span></div>
  </div>
  <div class="edu-metastrip"><div class="edu-meta"><div><span class="k">Autor</span><span class="v">Nicolás Bargioni</span></div><div><span class="k">Rol</span><span class="v">Data Scientist</span></div><div><span class="k">Categoría</span><span class="v">Cloud &amp; Deploy</span></div><div><span class="k">Dataset</span><span class="v">California Housing</span></div></div></div>
</div></div>'''))

## 🧭 Marco del trabajo

| | |
|---|---|
| **Objetivo** | estimar `MedHouseVal` (variable continua) a partir de los atributos sobre el dataset California Housing. |
| **Hipótesis** | Existen relaciones no lineales que el ensemble captura mejor que el modelo lineal. |
| **Datos** | 20640 bloques censales; ingreso, ocupación, ubicación → valor medio de vivienda. |
| **Metodología** | EDA exhaustivo → preprocesamiento (imputación/escalado/encoding) → LinearReg vs. RandomForest → evaluación en test (datos no vistos). |
| **Métrica** | R² / RMSE |

> Ejecutable top-down · `random_state=42` · preprocesamiento **sin data leakage**.

## 🛠 0 · Setup

Dependencias, imports y configuración global (reproducibilidad).

In [2]:
# 0.1 Dependencias (Colab ya trae casi todo; instala solo lo que falte)
import importlib, sys, subprocess
for _p in ['datasets', 'plotly']:
    if importlib.util.find_spec(_p) is None:
        subprocess.run([sys.executable, '-m', 'pip', '-q', 'install', _p])

# 0.2 Imports
import warnings; warnings.filterwarnings('ignore')
import numpy as np, pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
import plotly.subplots as sp
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold, KFold
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

# 0.3 Configuración global (reproducibilidad + estética de los gráficos)
SEED = 42
np.random.seed(SEED)
pd.set_option('display.max_columns', 60)
PRIMARY, ACCENT, TEAL = '#7fd4ff', '#ff9f5c', '#43c4b0'
COLORWAY = ['#7fd4ff', '#ff9f5c', '#43c4b0', '#bfe6ff', '#ffd9b8', '#5ce0b5']
pio.templates.default = 'plotly_dark'   # coherente con la estética oscura del notebook
px.defaults.color_discrete_sequence = COLORWAY
px.defaults.template = 'plotly_dark'
print('Setup OK · pandas', pd.__version__, '· plotly listo (gráficos interactivos)')

error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try brew install
    xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a Python library that isn't in Homebrew,
    use a virtual environment:
    
    python3 -m venv path/to/venv
    source path/to/venv/bin/activate
    python3 -m pip install xyz
    
    If you wish to install a Python application that isn't in Homebrew,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. You can install pipx with
    
    brew install pipx
    
    You may restore the old behavior of pip by passing
    the '--break-system-packages' flag to pip, or by adding
    'break-system-packages = true' to your pip.conf file. The latter
    will permanently disable this error.
    
    If you disable this error, we STRONGLY recommend that you additionally
    pass the '--user' flag to pip, or set 

Setup OK · pandas 2.3.3 · plotly listo (gráficos interactivos)


## 📥 1 · Carga de datos

Lectura del dataset y vista inicial de la tabla.

In [3]:
from sklearn.datasets import fetch_california_housing
d=fetch_california_housing(as_frame=True); df=d.frame.sample(6000, random_state=42)
print(df.shape)

(6000, 9)


In [4]:
# Vista rápida (el loader debe dejar un DataFrame `df`)
assert 'df' in globals(), 'El loader debe definir un DataFrame llamado df'
df = df.copy()
print('Filas × columnas:', df.shape)
df.head()

Filas × columnas: (6000, 9)


,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
20046,1.6812,25.0,4.192201,1.022284,1392.0,3.877437,36.06,-119.01,0.47700
3024,2.5313,30.0,5.039384,1.193493,1565.0,2.679795,35.14,-119.46,0.45800
15663,3.4801,52.0,3.977155,1.185877,1310.0,1.360332,37.80,-122.44,5.00001
20484,5.7376,17.0,6.163636,1.020202,1705.0,3.444444,34.28,-118.72,2.18600
9814,3.7250,34.0,5.492991,1.028037,1063.0,2.483645,36.62,-121.93,2.78000


## 🔍 2 · Análisis exploratorio (EDA)

Forma, tipos, faltantes, distribuciones, cardinalidad, correlaciones, outliers y relación con el target.

In [5]:
# 2.1 Forma, tipos y memoria
print('Dimensiones:', df.shape)
num_cols = df.select_dtypes(include='number').columns.tolist()
cat_cols = df.select_dtypes(exclude='number').columns.tolist()
print(f'{len(num_cols)} numéricas · {len(cat_cols)} categóricas')
display(df.dtypes.value_counts().rename('columnas').to_frame())
df.info()

Dimensiones: (6000, 9)
9 numéricas · 0 categóricas


,columnas
float64,9


<class 'pandas.core.frame.DataFrame'>
Index: 6000 entries, 20046 to 12033
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   MedInc       6000 non-null   float64
 1   HouseAge     6000 non-null   float64
 2   AveRooms     6000 non-null   float64
 3   AveBedrms    6000 non-null   float64
 4   Population   6000 non-null   float64
 5   AveOccup     6000 non-null   float64
 6   Latitude     6000 non-null   float64
 7   Longitude    6000 non-null   float64
 8   MedHouseVal  6000 non-null   float64
dtypes: float64(9)
memory usage: 468.8 KB


In [6]:
# 2.2 Valores faltantes
na = df.isna().sum(); na = na[na > 0].sort_values()
if len(na):
    display(pd.DataFrame({'faltantes': na[::-1], '%': (na[::-1]/len(df)*100).round(2)}))
    fig = px.bar(x=na.values, y=na.index, orientation='h',
                 labels={'x': 'cantidad', 'y': ''}, title='Valores faltantes por columna')
    fig.update_traces(marker_color=PRIMARY); fig.update_layout(height=80+34*len(na)); fig.show()
else:
    print('Sin valores faltantes.')

Sin valores faltantes.


In [7]:
# 2.3 Variable objetivo
TARGET = "MedHouseVal"
if TARGET and TARGET in df.columns:
    if "regresion" == 'regresion':
        display(df[TARGET].describe().to_frame())
        px.histogram(df, x=TARGET, nbins=40, title=f'Distribución de {TARGET}').show()
    else:
        vc = df[TARGET].value_counts(dropna=False)
        display(pd.DataFrame({'n': vc, '%': (vc/len(df)*100).round(2)}))
        px.bar(x=vc.index.astype(str), y=vc.values, labels={'x': TARGET, 'y': 'n'},
               title=f'Balance de clases — {TARGET}').show()
        imb = vc.min()/vc.max()
        print(f'Ratio min/max de clases: {imb:.2f}' + ('  ⚠️ desbalanceado' if imb < 0.4 else ''))
else:
    print('Sin target supervisado en esta etapa.')

,MedHouseVal
count,6000.000000
mean,2.067518
std,1.146332
min,0.149990
25%,1.203750
50%,1.808000
75%,2.656000
max,5.000010


In [8]:
# 2.4 Distribuciones de variables numéricas
num_cols = df.select_dtypes(include='number').columns.tolist()
if num_cols:
    display(df[num_cols].describe().T)
    cols = num_cols[:9]; rows = (len(cols)+2)//3
    fig = sp.make_subplots(rows=rows, cols=3, subplot_titles=cols)
    for i, col in enumerate(cols):
        fig.add_trace(go.Histogram(x=df[col].dropna(), marker_color=PRIMARY, name=col),
                      row=i//3+1, col=i%3+1)
    fig.update_layout(height=300*rows, showlegend=False, title_text='Distribuciones numéricas',
                      template='plotly_dark'); fig.show()
else:
    print('Sin columnas numéricas.')

,count,mean,std,min,25%,50%,75%,max
MedInc,6000.0,3.862622,1.896758,0.499900,2.556650,3.530750,4.728400,15.000100
HouseAge,6000.0,28.731000,12.503801,1.000000,18.000000,29.000000,37.000000,52.000000
AveRooms,6000.0,5.416648,2.551257,0.846154,4.422689,5.228359,6.042284,132.533333
AveBedrms,6000.0,1.094344,0.537988,0.500000,1.004473,1.047068,1.097450,34.066667
Population,6000.0,1418.065833,1113.279184,8.000000,777.000000,1159.000000,1717.000000,16305.000000
AveOccup,6000.0,2.960085,1.536514,1.263566,2.431564,2.823267,3.287626,83.171429
Latitude,6000.0,35.588290,2.135730,32.540000,33.920000,34.220000,37.700000,41.860000
Longitude,6000.0,-119.533267,2.005730,-124.250000,-121.770000,-118.470000,-117.990000,-114.580000
MedHouseVal,6000.0,2.067518,1.146332,0.149990,1.203750,1.808000,2.656000,5.000010


In [9]:
# 2.5 Categóricas: cardinalidad y valores frecuentes
cat_cols = df.select_dtypes(exclude='number').columns.tolist()
if cat_cols:
    card = df[cat_cols].nunique().sort_values(ascending=False)
    display(card.rename('valores únicos').to_frame())
    for col in card.index[:4]:
        print(f'\n{col} — top 6:'); print(df[col].value_counts(dropna=False).head(6))
else:
    print('Sin columnas categóricas.')

Sin columnas categóricas.


In [10]:
# 2.6 Matriz de correlación (numéricas)
num_cols = df.select_dtypes(include='number').columns.tolist()
if len(num_cols) >= 2:
    corr = df[num_cols].corr(numeric_only=True).round(2)
    fig = px.imshow(corr, color_continuous_scale='RdBu_r', zmin=-1, zmax=1, aspect='auto',
                    text_auto=(len(num_cols) <= 12), title='Matriz de correlación')
    fig.show()
else:
    print('Pocas numéricas para correlación.')

In [11]:
# 2.7 Outliers por regla IQR
num_cols = df.select_dtypes(include='number').columns.tolist()
rows = []
for col in num_cols:
    q1, q3 = df[col].quantile([.25, .75]); iqr = q3 - q1
    n = int(((df[col] < q1-1.5*iqr) | (df[col] > q3+1.5*iqr)).sum())
    rows.append((col, n, round(n/len(df)*100, 2)))
if rows:
    display(pd.DataFrame(rows, columns=['columna','outliers','%']).sort_values('outliers', ascending=False))
else:
    print('Sin numéricas para evaluar outliers.')

,columna,outliers,%
3,AveBedrms,396,6.60
4,Population,350,5.83
8,MedHouseVal,291,4.85
5,AveOccup,203,3.38
0,MedInc,202,3.37
2,AveRooms,136,2.27
1,HouseAge,0,0.00
6,Latitude,0,0.00
7,Longitude,0,0.00


### 🔍 Cómo leer este EDA

El EDA no es decorativo: **cada hallazgo condiciona una decisión de modelado**.

- **Faltantes** -> definen la estrategia de imputación. Pocos nulos se imputan (mediana en numéricas, moda en categóricas); demasiados pueden justificar descartar la columna.
- **Distribución / balance del target** -> si las clases están desbalanceadas, la *accuracy* engaña; por eso más abajo evaluamos con **ROC-AUC / F1-macro**. En regresión, un target muy sesgado puede pedir transformaciones (log).
- **Distribuciones y outliers** -> sesgos fuertes y valores extremos favorecen escalado robusto y modelos de árboles (que no asumen normalidad).
- **Correlaciones** -> variables muy correlacionadas aportan información redundante (afecta más a modelos lineales que a árboles) y pueden anticipar multicolinealidad.
- **Cardinalidad de categóricas** -> una cardinalidad alta hace explotar el *one-hot encoding*; conviene vigilarla antes de preprocesar.

#### Lectura concreta de este dataset (6000 x 9)

- **Faltantes: ninguno.** Las 9 columnas son `float64` y están completas (6000 non-null cada una), así que la imputación por mediana queda como salvaguarda del pipeline más que como necesidad real. Tampoco hay columnas categóricas: el dataset es 100% numérico.
- **Target `MedHouseVal` (continuo, no clases):** media 2.07, mediana 1.81, std 1.15, rango 0.15-5.00. La cola está **truncada artificialmente en 5.0** (techo de capping del censo), lo que infla la masa de valores en ese extremo y limita el techo de predicción del modelo.
- **Correlaciones:** la relación más fuerte de todo el dataset es **Latitude-Longitude = -0.93** (puro artefacto geográfico de California, no señal predictiva) y **AveRooms-AveBedrms = 0.86** (multicolinealidad esperable entre habitaciones y dormitorios). Frente al target, el predictor dominante es **MedInc (ingreso medio) = 0.69**; el resto aporta correlaciones lineales débiles (|r| <= 0.15), lo que anticipa que un modelo puramente lineal se quedará corto.
- **Outliers (regla IQR):** los más cargados son **AveBedrms 6.60%**, **Population 5.83%** y el propio **MedHouseVal 4.85%**; `HouseAge`, `Latitude` y `Longitude` no presentan outliers IQR. Estos extremos refuerzan la elección de un ensemble de árboles, robusto a colas pesadas.

## 🧪 3 · Preprocesamiento

Split antes de transformar; imputación, escalado y encoding dentro de un `Pipeline` (ajustado solo con train → sin leakage).

### 🧪 Por qué este preprocesamiento

- **Primero separar, después transformar.** Si imputáramos o escaláramos con todo el dataset, el test "filtraría" información al entrenamiento (*data leakage*) y las métricas saldrían infladas. Por eso el split va **antes** y las transformaciones se ajustan **solo con train**, encapsuladas en un `Pipeline`.
- **Imputación:** mediana en numéricas (robusta a outliers), moda en categóricas.
- **Escalado** (`StandardScaler`): media 0, desvío 1. Crítico para modelos sensibles a la escala (lineales, basados en distancias); los árboles no lo necesitan, pero no se perjudican.
- **Encoding** (`OneHotEncoder`, `handle_unknown='ignore'`): categóricas → columnas binarias, tolerando categorías nuevas en test.
- **Split estratificado** (clasificación): preserva la proporción de clases en train y test.

In [12]:
# 3.1 X / y y split train/test (estratificado si es clasificación)
TARGET = "MedHouseVal"
assert TARGET in df.columns, f'Target no encontrado: {TARGET}'
X = df.drop(columns=[TARGET]); y = df[TARGET]
strat = y if "regresion" == 'clasificacion' else None
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=SEED, stratify=strat)
print('train:', X_train.shape, '· test:', X_test.shape)

train: (4800, 8) · test: (1200, 8)


In [13]:
# 3.2 Preprocesador (se ajusta SOLO con train dentro del Pipeline → sin leakage)
num_feats = X_train.select_dtypes(include='number').columns.tolist()
cat_feats = X_train.select_dtypes(exclude='number').columns.tolist()
numeric = Pipeline([('imp', SimpleImputer(strategy='median')), ('sc', StandardScaler())])
categ = Pipeline([('imp', SimpleImputer(strategy='most_frequent')),
                  ('oh', OneHotEncoder(handle_unknown='ignore', sparse_output=False))])
preprocess = ColumnTransformer([('num', numeric, num_feats), ('cat', categ, cat_feats)])
print(f'{len(num_feats)} numéricas + {len(cat_feats)} categóricas → preprocesador listo')

8 numéricas + 0 categóricas → preprocesador listo


## 🧠 4 · Modelado

Baseline interpretable vs. ensemble, comparados con validación cruzada.

### 🧠 Qué modelos y por qué

1. **Regresión lineal** -- *baseline* interpretable: asume relación lineal entre features y target.
2. **Random Forest Regressor** -- *ensemble* que captura no linealidades e interacciones sin que tengamos que especificarlas.

**Hiperparámetros**: defaults sensatos (`n_estimators=300`, `random_state=42`), sin tuning todavía. **Validación cruzada 5-fold** con **R2** como métrica: una estimación promediada del poder explicativo, más confiable que un único split.

#### Qué pasó al entrenar

El ensemble ganó con holgura. **RandomForest alcanzó R2 = 0.760 +/- 0.024** en validación cruzada, frente a **0.473 +/- 0.224** de la regresión lineal: una mejora de **delta +0.287** de varianza explicada. Más allá del promedio, la diferencia clave está en la **estabilidad**: el desvío del baseline lineal (+/-0.224) es casi diez veces mayor que el del bosque (+/-0.024), señal de que la regresión lineal es muy sensible al fold (probablemente por los extremos y la no linealidad geográfica), mientras que el RandomForest generaliza de forma consistente entre particiones. No hubo empate: el problema **no es lineal**, y el ensemble lo confirma.

In [14]:
# 4 · Candidatos (baseline + ensemble) con validación cruzada
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
cv = KFold(n_splits=5, shuffle=True, random_state=SEED)
cands = {'LinReg (baseline)': LinearRegression(),
         'RandomForest': RandomForestRegressor(n_estimators=300, random_state=SEED, n_jobs=-1)}
results = {}
for name, reg in cands.items():
    pipe = Pipeline([('prep', preprocess), ('reg', reg)])
    sc = cross_val_score(pipe, X_train, y_train, cv=cv, scoring='r2', n_jobs=-1)
    results[name] = sc; print(f'{name:22s} R2: {sc.mean():.4f} ± {sc.std():.4f}')
best_name = max(results, key=lambda k: results[k].mean()); _b = next(k for k in results if 'baseline' in k.lower())
print(f'\nMejor modelo: {best_name} = {results[best_name].mean():.3f} · baseline {results[_b].mean():.3f} (Δ {results[best_name].mean()-results[_b].mean():+.3f})')
best = Pipeline([('prep', preprocess), ('reg', cands[best_name])]).fit(X_train, y_train)

LinReg (baseline)      R2: 0.4728 ± 0.2236


RandomForest           R2: 0.7596 ± 0.0243

Mejor modelo: RandomForest = 0.760 · baseline 0.473 (Δ +0.287)


## 📊 5 · Evaluación

Desempeño sobre datos nunca vistos (set de test).

In [15]:
# 5 · Evaluación en test (datos nunca vistos)
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
y_pred = best.predict(X_test)
print(f'R2  : {r2_score(y_test, y_pred):.4f}')
print(f'MAE : {mean_absolute_error(y_test, y_pred):.4f}')
print(f'RMSE: {mean_squared_error(y_test, y_pred)**0.5:.4f}')
lims = [float(min(y_test.min(), y_pred.min())), float(max(y_test.max(), y_pred.max()))]
fig = px.scatter(x=y_test, y=y_pred, opacity=.5, labels={'x': 'real', 'y': 'predicho'},
                 title='Predicho vs. real')
fig.update_traces(marker_color=PRIMARY)
fig.add_trace(go.Scatter(x=lims, y=lims, mode='lines', line=dict(dash='dash', color=ACCENT), showlegend=False))
fig.show()

R2  : 0.7714
MAE : 0.3799
RMSE: 0.5583


### 📌 Lectura de resultados

Sobre 1200 viviendas nunca vistas, el RandomForest explica el **77% de la varianza** (R2 0.7714) con un error medio absoluto de **0.380** (~38.000 USD) y un RMSE de **0.558**. La consistencia entre validación cruzada (R2 0.760 +/- 0.024) y test (0.771) descarta overfitting: el modelo generaliza. El salto frente al baseline lineal (R2 0.473) confirma que **California Housing es un problema no lineal**, dominado por `MedInc` pero con interacciones geográficas que solo el ensemble captura. La brecha RMSE/MAE (~1.47x) revela que los errores grandes se concentran en las viviendas caras **truncadas en el techo de 5.0**, donde el modelo no puede predecir por encima del límite del dataset. La palanca de mejora más clara es el feature engineering geográfico, no más árboles.

### 📊 Cómo interpretar estas métricas

- **R2**: proporción de varianza explicada (1 = perfecto; 0 = no mejor que predecir la media; negativo = peor que la media).
- **MAE**: error absoluto medio, en las **unidades del target** (lectura directa).
- **RMSE**: penaliza más los errores grandes; si **RMSE >> MAE**, hay outliers con error alto.
- **Predicho vs. real**: los puntos deberían alinearse sobre la diagonal; desvíos sistemáticos = sesgo del modelo.

#### Interpretación de los números reales (1200 casos de test nunca vistos)

- **R2 = 0.7714** -> el modelo explica el **77% de la varianza** del valor de vivienda. Es coherente con el R2 de validación cruzada (0.760), incluso ligeramente mejor: **no hay señales de overfitting**, el desempeño se sostiene fuera de muestra.
- **MAE = 0.3799** -> en promedio el modelo se equivoca por **~38.000 USD** (el target está en cientos de miles de dólares), un error razonable frente a una media de 2.07 (~207.000 USD).
- **RMSE = 0.5583** -> el RMSE es **~1.47x el MAE**, una brecha moderada que confirma lo visto en el EDA: existen **errores grandes puntuales**, concentrados sobre todo en las viviendas caras truncadas en el techo de 5.0, donde el modelo no puede predecir por encima del límite del dataset.
- **Qué se infiere:** el grueso del poder predictivo proviene de `MedInc` (r = 0.69 con el target), pero el salto de 0.47 a 0.77 de R2 respecto del baseline lineal demuestra que el RandomForest captura **no linealidades e interacciones geográficas** (Latitude/Longitude) que la regresión lineal ignora.

**Limitación**: sin tuning; probar regularización (Ridge/Lasso) y *feature engineering* (p. ej. distancia a la costa, ratio habitaciones/población) para atacar el error residual en la cola cara.

## ✅ Conclusiones

- El EDA mapeó un dataset **limpio (6000 x 9, sin faltantes, todo numérico)**, con el target `MedHouseVal` sesgado y **truncado en 5.0**, y outliers concentrados en `AveBedrms` (6.6%) y `Population` (5.8%).
- El predictor dominante es **`MedInc` (r = 0.69 con el target)**; las correlaciones más fuertes del dataset (Latitude-Longitude -0.93, AveRooms-AveBedrms 0.86) son redundancias geográficas y estructurales más que señal directa.
- El preprocesamiento vivió dentro de un **Pipeline** ajustado solo con train -> **sin data leakage** (split 4800 / 1200).
- **RandomForest superó al baseline lineal por amplio margen**: R2 0.760 +/- 0.024 vs. 0.473 +/- 0.224 en CV (**delta +0.287**), y un test de **R2 0.771 . MAE 0.380 . RMSE 0.558**. El problema es claramente **no lineal** y el ensemble lo aprovecha con mucha más estabilidad entre folds.
- **Próximos pasos**: feature engineering de dominio (distancia a la costa, densidad, ratios), tuning de hiperparámetros y modelar el sesgo de la cola cara truncada en 5.0 para reducir el RMSE residual.

---
*Nicolás Bargioni · Data Scientist · [nicolasbargioni.com](https://nicolasbargioni.com)*