# Pima Diabetes: Clustering & PCA
*Clustering & PCA · Data & Machine Learning*

In [1]:
#@title 📌 Portada
from IPython.display import HTML, display
display(HTML(r'''<style>
  @import url('https://fonts.googleapis.com/css2?family=Archivo+Black&family=Archivo:wght@400;500;600;700&family=Archivo+Expanded:wght@600;700;800&display=swap');

  /* ===================================================================
     SISTEMA EDITORIAL CINEMATOGRÁFICO OSCURO
     Paleta fría documental · tipografía display extruida · vidrio esmerilado
     =================================================================== */

  /* ---------- contenedor base ---------- */
  .edu{max-width:1140px;margin:24px auto;font-family:'Archivo',system-ui,sans-serif;
       color:#dde7f2;line-height:1.66;font-size:15px;}
  .edu *{box-sizing:border-box;}

  /* ---------- hoja: panel de vidrio oscuro ---------- */
  .edu-sheet{position:relative;overflow:hidden;border-radius:22px;padding:36px 44px 40px;
     color:#e6eef8;background:linear-gradient(168deg,rgba(17,30,47,.94),rgba(9,16,27,.96));
     border:1px solid rgba(140,180,224,.14);
     box-shadow:0 30px 70px rgba(3,8,18,.55),inset 0 1px 0 rgba(255,255,255,.05);}
  .edu-sheet::before{content:"";position:absolute;top:0;left:0;right:0;height:4px;
     background:linear-gradient(90deg,#1d6fb0,#43c4b0 35%,#7fd4ff 55%,#43c4b0 75%,#1d6fb0);
     background-size:220% 100%;animation:eduBarFlow 7s linear infinite;}
  .edu-sheet::after{content:"";position:absolute;inset:0;pointer-events:none;z-index:0;opacity:.5;
     background:radial-gradient(110% 60% at 88% -10%,rgba(127,212,255,.10),transparent 60%);}
  .edu-sheet>*{position:relative;z-index:1;}

  /* ---------- eyebrow / etiqueta ---------- */
  .edu-eyebrow{display:inline-block;font-family:'Archivo Expanded','Archivo',sans-serif;
     font-size:10.5px;font-weight:700;letter-spacing:3px;text-transform:uppercase;color:#7fd4ff;
     background:rgba(127,212,255,.08);border:1px solid rgba(127,212,255,.30);
     padding:6px 16px;border-radius:999px;margin-bottom:18px;animation:eduPulse 3.4s ease-in-out infinite;}

  /* ---------- títulos ---------- */
  .edu h2{font-family:'Archivo Expanded','Archivo',sans-serif;color:#f1f7ff;font-size:23px;
     font-weight:800;letter-spacing:.3px;text-transform:uppercase;margin:34px 0 14px;
     padding:6px 0 10px 18px;border-left:4px solid #43c4b0;
     background:linear-gradient(90deg,rgba(67,196,176,.12),transparent 60%);}
  .edu h2:first-child{margin-top:0;}
  .edu h2.alt{border-left-color:#ff8f6b;background:linear-gradient(90deg,rgba(255,143,107,.13),transparent 60%);}
  .edu h3{color:#7fd4ff;font-size:12px;font-weight:700;letter-spacing:1.4px;
     text-transform:uppercase;margin:22px 0 6px;font-family:'Archivo Expanded','Archivo',sans-serif;}
  .edu p{margin:9px 0;color:#cdd9e7;}
  .edu b,.edu strong{color:#ffffff;font-weight:700;}
  .edu i,.edu em{color:#bfe6ff;}
  .edu code{background:rgba(127,212,255,.12);border:1px solid rgba(127,212,255,.26);border-radius:5px;
     padding:1px 7px;font-size:13px;color:#bfe6ff;font-family:ui-monospace,Menlo,monospace;}

  /* ---------- listas con viñeta propia ---------- */
  .edu ul{margin:6px 0;padding-left:2px;list-style:none;}
  .edu ul li{position:relative;padding-left:26px;margin:8px 0;color:#cdd9e7;}
  .edu ul li::before{content:"";position:absolute;left:4px;top:9px;width:8px;height:8px;border-radius:2px;
     background:linear-gradient(135deg,#7fd4ff,#43c4b0);transform:rotate(45deg);box-shadow:0 0 8px rgba(127,212,255,.5);}

  /* ---------- tablas ---------- */
  .edu-tbl{border-collapse:separate;border-spacing:0;width:100%;font-size:14px;margin:16px 0;
     border:1px solid rgba(140,180,224,.16);border-radius:14px;overflow:hidden;
     background:rgba(8,15,26,.45);box-shadow:0 10px 30px rgba(3,8,18,.4);}
  .edu-tbl th{background:linear-gradient(135deg,#103a5e,#1c6aa6);color:#eaf4ff;font-weight:700;
     padding:12px 15px;text-align:left;letter-spacing:.4px;border:none;
     font-family:'Archivo Expanded','Archivo',sans-serif;font-size:12px;text-transform:uppercase;}
  .edu-tbl td{padding:10px 15px;border:none;border-top:1px solid rgba(140,180,224,.10);color:#d4e0ee;}
  .edu-tbl tr:nth-child(even) td{background:rgba(255,255,255,.025);}
  .edu-tbl tr:hover td{background:rgba(127,212,255,.10);}
  .edu-tbl .num,.edu-tbl td.num{text-align:right;font-variant-numeric:tabular-nums;}

  /* ---------- grid de tarjetas ---------- */
  .edu-grid{display:flex;flex-wrap:wrap;gap:16px;margin:16px 0;}
  .edu-card{flex:1 1 220px;border-radius:16px;padding:18px 20px;
     background:linear-gradient(160deg,rgba(24,40,60,.6),rgba(13,23,37,.5));
     border:1px solid rgba(140,180,224,.16);transition:transform .18s ease,box-shadow .18s ease,border-color .18s ease;}
  .edu-card:hover{transform:translateY(-4px);box-shadow:0 16px 34px rgba(3,8,18,.5);border-color:rgba(127,212,255,.4);}
  .edu-card h3{margin:0 0 6px;}
  .edu-card p{margin:0;font-size:14px;color:#aebfd2;line-height:1.5;}

  /* ---------- KPIs / cifras ---------- */
  .edu-kpis{display:flex;flex-wrap:wrap;gap:14px;margin:18px 0;}
  .edu-kpi{flex:1 1 150px;text-align:center;border-radius:16px;padding:18px 14px;
     background:linear-gradient(165deg,rgba(20,38,58,.7),rgba(10,18,30,.6));
     border:1px solid rgba(140,180,224,.18);box-shadow:inset 0 1px 0 rgba(255,255,255,.05);}
  .edu-kpi .v{font-size:30px;font-weight:800;color:#7fd4ff;line-height:1;
     font-family:'Archivo Expanded','Archivo',sans-serif;text-shadow:0 0 22px rgba(127,212,255,.4);}
  .edu-kpi .l{font-size:10.5px;text-transform:uppercase;letter-spacing:1.2px;color:#8ea3ba;margin-top:8px;}

  /* ---------- callouts ---------- */
  .edu-note,.edu-warn,.edu-ok{border-radius:14px;padding:15px 20px;margin:16px 0;font-size:14px;
     line-height:1.62;border:1px solid;border-left-width:4px;backdrop-filter:blur(4px);}
  .edu-note{background:rgba(47,159,224,.10);border-color:rgba(127,212,255,.26);border-left-color:#7fd4ff;color:#cfe7fb;}
  .edu-warn{background:rgba(255,160,90,.10);border-color:rgba(255,180,110,.30);border-left-color:#ff9f5c;color:#ffd9b8;}
  .edu-ok{background:rgba(67,196,176,.10);border-color:rgba(90,220,190,.30);border-left-color:#43c4b0;color:#bff0e4;}
  .edu-note b,.edu-warn b,.edu-ok b{color:#fff;}

  /* ---------- spans destacados ---------- */
  .edu .hl{color:#7fd4ff;font-weight:700;} .edu .ok{color:#5ce0b5;font-weight:700;}
  .edu .warn{color:#ff9f5c;font-weight:700;}

  /* ---------- caption / pie ---------- */
  .edu-cap{font-size:12.5px;color:#8295ab;margin-top:12px;}
  .edu-foot{font-size:12.5px;color:#8295ab;margin-top:22px;border-top:1px dashed rgba(140,180,224,.22);padding-top:14px;}

  /* ---------- referencias ---------- */
  .edu-ref{background:rgba(8,16,28,.5);border:1px solid rgba(140,180,224,.16);border-left:4px solid #7fd4ff;
     border-radius:12px;padding:18px 20px;font-size:13.5px;color:#b9c8da;line-height:1.75;}

  /* ===================================================================
     PORTADA · HERO CINEMATOGRÁFICO
     =================================================================== */
  .edu-portada{max-width:1180px;margin:26px auto;border-radius:26px;overflow:hidden;
     font-family:'Archivo',system-ui,sans-serif;color:#e9f1fb;border:1px solid rgba(120,160,210,.18);
     box-shadow:0 40px 90px rgba(2,6,14,.6);animation:eduBreathe 12s ease-in-out infinite;}

  .edu-cine{position:relative;overflow:hidden;padding:26px 52px 24px 78px;min-height:560px;
     background:
        radial-gradient(60% 42% at 78% 6%,rgba(170,210,255,.20),transparent 55%),
        radial-gradient(80% 60% at 6% 104%,rgba(40,150,140,.20),transparent 60%),
        linear-gradient(180deg,#0c1a2b 0%,#0a1626 42%,#060f1b 100%);
     background-size:130% 130%,100% 100%,100% 100%;animation:eduHeroFlow 20s ease infinite;}

  /* atmósfera: niebla, grano, montañas, estrellas, cometas (todo CSS, sin imágenes externas) */
  .edu-fog{position:absolute;inset:0;z-index:0;pointer-events:none;
     background:radial-gradient(50% 38% at 50% 26%,rgba(150,190,230,.16),transparent 72%);filter:blur(14px);
     animation:eduFog 16s ease-in-out infinite;}
  .edu-grain{position:absolute;inset:0;z-index:2;pointer-events:none;opacity:.32;mix-blend-mode:overlay;
     background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='120' height='120'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='2' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E");}
  .edu-ridge{position:absolute;left:0;right:0;bottom:0;width:100%;height:190px;z-index:1;pointer-events:none;display:block;}
  .edu-stars,.edu-stars2{position:absolute;inset:0;pointer-events:none;z-index:1;}
  .edu-stars{animation:eduTwinkle 4.5s ease-in-out infinite;background-image:
     radial-gradient(1px 1px at 12% 22%,#fff,transparent),radial-gradient(1px 1px at 28% 64%,#fff,transparent),
     radial-gradient(1px 1px at 44% 14%,#fff,transparent),radial-gradient(1px 1px at 63% 38%,#fff,transparent),
     radial-gradient(1px 1px at 82% 33%,#fff,transparent),radial-gradient(1px 1px at 91% 20%,#fff,transparent),
     radial-gradient(1px 1px at 7% 48%,#fff,transparent),radial-gradient(1px 1px at 35% 12%,#fff,transparent);}
  .edu-stars2{animation:eduTwinkle 7s ease-in-out infinite;animation-delay:1.6s;background-image:
     radial-gradient(1.6px 1.6px at 18% 30%,#bfefff,transparent),radial-gradient(1.6px 1.6px at 49% 20%,#ffe9a8,transparent),
     radial-gradient(1.6px 1.6px at 70% 12%,#fff,transparent),radial-gradient(1.6px 1.6px at 88% 28%,#9fe6da,transparent),
     radial-gradient(1.6px 1.6px at 24% 18%,#fff,transparent);}
  .edu-comet{position:absolute;top:14%;left:-15%;width:160px;height:2px;z-index:1;pointer-events:none;
     background:linear-gradient(90deg,transparent,#bfefff,#fff);border-radius:50%;opacity:0;
     box-shadow:0 0 8px #bfefff,0 0 24px rgba(150,210,255,.55);transform:rotate(15deg);
     animation:eduComet 13s linear infinite;}
  .edu-comet.edu-comet2{top:40%;animation-duration:17s;animation-delay:7s;}

  .edu-cine>*{position:relative;z-index:3;}

  /* nav superior */
  .edu-nav{display:flex;justify-content:space-between;align-items:center;gap:18px;flex-wrap:wrap;
     padding-bottom:8px;border-bottom:1px solid rgba(160,195,235,.12);}
  .edu-logo{font-family:'Archivo Black',sans-serif;font-size:18px;letter-spacing:.5px;color:#fff;}
  .edu-logo span{color:#7fd4ff;font-weight:400;font-family:'Archivo',sans-serif;font-size:13px;margin-left:6px;letter-spacing:1px;}
  .edu-nav nav{display:flex;gap:22px;flex-wrap:wrap;}
  .edu-nav nav a{font-size:12.5px;letter-spacing:.6px;color:#aebfd2;text-decoration:none;text-transform:uppercase;
     font-weight:600;transition:color .15s ease;}
  .edu-nav nav a:hover{color:#fff;}
  .edu-nav nav a.on{color:#7fd4ff;}

  /* etiquetas verticales decorativas (borde izquierdo) */
  .edu-vlabels{position:absolute;left:20px;top:54%;transform:translateY(-50%);z-index:3;
     display:flex;flex-direction:column;gap:30px;}
  .edu-vlabels span{writing-mode:vertical-rl;transform:rotate(180deg);font-size:10px;letter-spacing:3px;
     text-transform:uppercase;color:rgba(174,191,210,.6);font-weight:600;
     font-family:'Archivo Expanded','Archivo',sans-serif;}

  /* layout principal: titular gigante a todo el ancho */
  .edu-cine-grid{margin-top:30px;}
  .edu-kicker{display:inline-block;font-family:'Archivo Expanded','Archivo',sans-serif;font-size:10.5px;
     font-weight:700;letter-spacing:3px;text-transform:uppercase;color:#8fb4d8;margin-bottom:18px;
     padding-left:2px;animation:eduRise .8s cubic-bezier(.2,.7,.2,1) both;}

  .edu-mega{font-family:'Archivo Black',sans-serif;text-transform:uppercase;color:#f6faff;margin:0;
     font-size:clamp(44px,6.6vw,92px);line-height:.9;letter-spacing:-.01em;
     text-shadow:0 1px 0 #c4cfdd,0 2px 0 #aeb9c9,0 3px 0 #99a5b8,0 4px 0 #8593a8,0 5px 0 #74829a,
                 0 12px 22px rgba(0,0,0,.6);animation:eduRise .9s cubic-bezier(.2,.7,.2,1) both;}
  .edu-mega em{display:block;font-style:normal;color:#7fd4ff;
     text-shadow:0 0 30px rgba(127,212,255,.55),0 3px 0 rgba(10,40,70,.5);}

  .edu-lede{max-width:480px;margin:24px 0 0;color:#c4d3e4;font-size:16px;line-height:1.6;
     animation:eduRise .9s cubic-bezier(.2,.7,.2,1) .15s both;}

  .edu-cta{display:inline-flex;align-items:center;gap:12px;margin-top:26px;cursor:pointer;
     padding:14px 26px;border-radius:999px;text-decoration:none;font-weight:700;font-size:14.5px;
     letter-spacing:.4px;color:#06121f;background:linear-gradient(135deg,#aee1ff,#7fd4ff);
     box-shadow:0 14px 34px rgba(127,212,255,.35);transition:transform .18s ease,box-shadow .18s ease;
     animation:eduRise .9s cubic-bezier(.2,.7,.2,1) .3s both;}
  .edu-cta:hover{transform:translateY(-2px);box-shadow:0 18px 42px rgba(127,212,255,.5);}
  .edu-cta span{transition:transform .18s ease;} .edu-cta:hover span{transform:translateX(5px);}

  /* tarjetas glassmorphic en fila horizontal (hallazgos) bajo el titular */
  .edu-floats{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px;margin-top:40px;}
  .edu-glass{position:relative;display:flex;flex-direction:column;border-radius:18px;padding:22px 24px;color:#e9f1fb;
     background:linear-gradient(160deg,rgba(22,38,58,.55),rgba(10,18,30,.42));
     backdrop-filter:blur(14px) saturate(130%);-webkit-backdrop-filter:blur(14px) saturate(130%);
     border:1px solid rgba(160,200,240,.18);box-shadow:0 20px 50px rgba(0,0,0,.45),inset 0 1px 0 rgba(255,255,255,.08);
     transition:transform .2s ease,border-color .2s ease;animation:eduRise .9s cubic-bezier(.2,.7,.2,1) both;}
  .edu-floats .edu-glass:nth-child(1){animation-delay:.35s;}
  .edu-floats .edu-glass:nth-child(2){animation-delay:.46s;}
  .edu-floats .edu-glass:nth-child(3){animation-delay:.57s;}
  .edu-glass:hover{transform:translateY(-4px);border-color:rgba(127,212,255,.5);}
  .edu-glass h4{margin:0 0 8px;font-size:17px;font-weight:700;color:#fff;font-family:'Archivo Expanded','Archivo',sans-serif;}
  .edu-glass p{margin:0;font-size:13.5px;line-height:1.55;color:#b6c6d8;}
  .edu-glass-foot{display:flex;justify-content:space-between;align-items:center;margin-top:auto;padding-top:16px;gap:10px;}
  .edu-metric{font-size:12px;font-weight:700;color:#7fd4ff;letter-spacing:.3px;}
  .edu-glass-foot a{font-size:12.5px;font-weight:700;color:#fff;text-decoration:none;white-space:nowrap;
     border-bottom:1px solid rgba(127,212,255,.5);padding-bottom:1px;transition:color .15s ease;}
  .edu-glass-foot a:hover{color:#7fd4ff;}

  /* fila de fuentes (logos) */
  .edu-logos{display:flex;align-items:center;gap:26px;flex-wrap:wrap;margin-top:38px;padding-top:18px;
     border-top:1px solid rgba(160,195,235,.12);}
  .edu-logos-label{font-size:10px;letter-spacing:2.5px;text-transform:uppercase;color:#6f86a0;font-weight:700;}
  .edu-logos>span:not(.edu-logos-label){font-family:'Archivo Expanded','Archivo',sans-serif;font-weight:700;
     font-size:13px;letter-spacing:.5px;color:rgba(190,205,222,.55);transition:color .18s ease;}
  .edu-logos>span:not(.edu-logos-label):hover{color:#cfe0f2;}

  /* franja de metadatos académicos bajo el hero */
  .edu-metastrip{background:linear-gradient(180deg,#0a131f,#0b1422);padding:26px 52px 30px;
     border-top:1px solid rgba(160,195,235,.10);}
  .edu-meta{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:18px;}
  .edu-meta>div{display:flex;flex-direction:column;gap:4px;}
  .edu-meta .k{font-size:10px;letter-spacing:1.8px;text-transform:uppercase;color:#7fd4ff;font-weight:700;
     font-family:'Archivo Expanded','Archivo',sans-serif;}
  .edu-meta .v{font-size:13.5px;color:#cdd9e7;line-height:1.45;}
  .edu-disc{background:rgba(255,170,90,.09);border:1px solid rgba(255,185,120,.28);border-left:4px solid #ff9f5c;
     color:#ffd9b8;border-radius:14px;padding:14px 18px;font-size:12.8px;margin-top:22px;line-height:1.6;}
  .edu-disc b{color:#ffe9d2;}

  @media (max-width:820px){
     .edu-cine{padding:24px 30px 22px;min-height:auto;}
     .edu-floats{grid-template-columns:1fr;gap:14px;margin-top:30px;}
     .edu-vlabels{display:none;}
     .edu-nav nav{gap:14px;} .edu-sheet{padding:26px 22px 30px;}
  }

  /* ===================================================================
     ANIMACIONES
     =================================================================== */
  @keyframes eduBarFlow{0%{background-position:0% 0;}100%{background-position:220% 0;}}
  @keyframes eduPulse{0%,100%{box-shadow:0 0 0 rgba(127,212,255,0);}50%{box-shadow:0 0 16px rgba(127,212,255,.35);}}
  @keyframes eduHeroFlow{0%{background-position:0% 50%,0 0,0 0;}50%{background-position:100% 50%,0 0,0 0;}100%{background-position:0% 50%,0 0,0 0;}}
  @keyframes eduBreathe{0%,100%{box-shadow:0 40px 90px rgba(2,6,14,.6);}50%{box-shadow:0 46px 104px rgba(20,80,110,.5);}}
  @keyframes eduTwinkle{0%,100%{opacity:.35;}50%{opacity:1;}}
  @keyframes eduFog{0%,100%{opacity:.7;transform:translateX(0);}50%{opacity:1;transform:translateX(20px);}}
  @keyframes eduComet{0%{opacity:0;transform:translate(0,0) rotate(15deg);}5%{opacity:.95;}
     22%{opacity:0;transform:translate(1200px,330px) rotate(15deg);}100%{opacity:0;}}
  @keyframes eduRise{from{opacity:0;transform:translateY(20px);}to{opacity:1;transform:translateY(0);}}

  @media (prefers-reduced-motion:reduce){
     .edu-portada,.edu-cine,.edu-fog,.edu-stars,.edu-stars2,.edu-comet,.edu-sheet::before,.edu-eyebrow,
     .edu-kicker,.edu-mega,.edu-lede,.edu-cta,.edu-glass{animation:none!important;}
  }
</style><style>
.edu-banner{position:relative;overflow:hidden;border-radius:20px;margin:26px auto;max-width:1140px;
  padding:28px 42px;color:#e9f1fb;font-family:'Archivo',system-ui,sans-serif;line-height:1.62;font-size:15px;
  background:radial-gradient(72% 130% at 90% -25%,rgba(127,212,255,.16),transparent 60%),
             radial-gradient(80% 120% at 0% 132%,rgba(40,150,140,.14),transparent 60%),
             linear-gradient(168deg,#0c1a2b,#0a1626 58%,#060f1b);
  border:1px solid rgba(140,180,224,.16);box-shadow:0 30px 70px rgba(3,8,18,.5),inset 0 1px 0 rgba(255,255,255,.05);}
.edu-banner::before{content:"";position:absolute;top:0;left:0;right:0;height:4px;z-index:2;
  background:linear-gradient(90deg,#1d6fb0,#43c4b0 35%,#7fd4ff 55%,#43c4b0 75%,#1d6fb0);
  background-size:220% 100%;animation:eduBarFlow 7s linear infinite;}
.edu-banner>*{position:relative;z-index:1;}
.edu-banner .eb{display:inline-block;font-family:'Archivo Expanded','Archivo',sans-serif;font-size:10.5px;
  font-weight:700;letter-spacing:3px;text-transform:uppercase;color:#7fd4ff;
  background:rgba(127,212,255,.08);border:1px solid rgba(127,212,255,.30);padding:5px 15px;border-radius:999px;
  animation:eduPulse 3.4s ease-in-out infinite;}
.edu-banner h2{font-family:'Archivo Black',sans-serif;text-transform:uppercase;color:#f6faff;
  margin:15px 0 0;font-size:clamp(24px,3.2vw,38px);line-height:.96;letter-spacing:-.01em;
  text-shadow:0 2px 0 #8593a8,0 8px 18px rgba(0,0,0,.5);animation:eduRise .7s cubic-bezier(.2,.7,.2,1) both;}
.edu-banner h2 em{font-style:normal;color:#7fd4ff;text-shadow:0 0 26px rgba(127,212,255,.5);}
.edu-banner .lede{margin:14px 0 0;max-width:700px;color:#c4d3e4;font-size:15px;}
.edu-banner .step{position:absolute;right:34px;top:50%;transform:translateY(-50%);z-index:0;
  font-family:'Archivo Black',sans-serif;font-size:104px;line-height:1;color:rgba(127,212,255,.09);}
.edu-banner h3{font-family:'Archivo Expanded','Archivo',sans-serif;color:#7fd4ff;font-size:12px;
  letter-spacing:1.4px;text-transform:uppercase;margin:22px 0 6px;}
.edu-banner p{margin:8px 0;color:#cdd9e7;} .edu-banner b{color:#fff;}
.edu-banner ul{margin:10px 0 0;padding-left:2px;list-style:none;}
.edu-banner ul li{position:relative;padding-left:24px;margin:9px 0;color:#cdd9e7;}
.edu-banner ul li::before{content:"";position:absolute;left:3px;top:8px;width:8px;height:8px;border-radius:2px;
  background:linear-gradient(135deg,#7fd4ff,#43c4b0);transform:rotate(45deg);box-shadow:0 0 8px rgba(127,212,255,.5);}
.edu-banner .row{display:flex;gap:16px;margin:12px 0;padding:14px 18px;border-radius:13px;
  background:rgba(8,16,28,.5);border:1px solid rgba(140,180,224,.14);border-left:3px solid #43c4b0;}
.edu-banner .row.alt{border-left-color:#ff9f5c;}
.edu-banner .row .k{flex:0 0 132px;font:700 11px/1.5 'Archivo Expanded','Archivo',sans-serif;letter-spacing:1px;
  text-transform:uppercase;color:#ff9f5c;}
.edu-banner .row .v{flex:1;color:#dde7f2;font-size:14.5px;}
.edu-banner .foot{margin-top:22px;border-top:1px dashed rgba(140,180,224,.22);padding-top:13px;
  font-size:12.5px;color:#8295ab;}
@media (max-width:820px){.edu-banner{padding:22px 24px;} .edu-banner .step{display:none;}
  .edu-banner .row{flex-direction:column;gap:4px;} .edu-banner .row .k{flex:none;}}
</style><div style="filter:hue-rotate(62deg) saturate(1.0);"><div class="edu-portada">
  <div class="edu-cine">
     <div class="edu-fog"></div><div class="edu-stars"></div><div class="edu-stars2"></div>
     <span class="edu-comet"></span><span class="edu-comet edu-comet2"></span>
     <svg class="edu-ridge" viewBox="0 0 1200 200" preserveAspectRatio="none" aria-hidden="true">
        <defs><linearGradient id="eduRg" x1="0" y1="0" x2="0" y2="1">
        <stop offset="0" stop-color="#0d2034"/><stop offset="1" stop-color="#050b14"/></linearGradient></defs>
        <path d="M0,200 L0,118 L130,72 L250,112 L380,52 L520,118 L660,58 L800,116 L940,46 L1070,104 L1200,64 L1200,200 Z" fill="url(#eduRg)"/>
     </svg>
     <div class="edu-grain"></div>
     <header class="edu-nav"><div class="edu-logo">ds-colabs<span>· Data &amp; Machine Learning</span></div></header>
     <div class="edu-vlabels"><span>Kaggle/UCI (mirror)</span><span>Clustering</span><span>Coeficiente de silueta</span></div>
     <div class="edu-cine-grid"><div class="edu-cine-main">
        <span class="edu-kicker">Data &amp; Machine Learning · Clustering &amp; PCA</span>
        <h1 class="edu-mega">Pima Diabetes: Clustering &amp; PCA</h1>
        <p class="edu-lede">Segmentación no supervisada: elección de k por silueta e interpretación con PCA.</p>
        <a class="edu-cta" href="#">Explorar el análisis <span>&rarr;</span></a>
     </div>
     <aside class="edu-floats"><article class="edu-glass"><h4>Datos</h4><p>768 pacientes; 8 indicadores clínicos → diabetes (sí/no).</p><div class="edu-glass-foot"><span class="edu-metric">Kaggle/UCI (mirror)</span><a>Ver análisis &rarr;</a></div></article><article class="edu-glass"><h4>Enfoque</h4><p>Segmentación no supervisada: elección de k por silueta e interpretación con PCA.</p><div class="edu-glass-foot"><span class="edu-metric">K-Means (codo + silueta) + PCA</span><a>Ver análisis &rarr;</a></div></article><article class="edu-glass"><h4>Métrica</h4><p>Se evalúa con Coeficiente de silueta.</p><div class="edu-glass-foot"><span class="edu-metric">Rigor</span><a>Ver análisis &rarr;</a></div></article></aside></div>
     <div class="edu-logos"><span class="edu-logos-label">Fuentes</span><span>Kaggle</span><span>Hugging Face</span><span>scikit-learn</span><span>Google Colab</span></div>
  </div>
  <div class="edu-metastrip"><div class="edu-meta"><div><span class="k">Autor</span><span class="v">Nicolás Bargioni</span></div><div><span class="k">Rol</span><span class="v">Data Scientist</span></div><div><span class="k">Categoría</span><span class="v">Data &amp; Machine Learning</span></div><div><span class="k">Dataset</span><span class="v">Pima Diabetes</span></div></div></div>
</div></div>'''))

## 🧭 Marco del trabajo

| | |
|---|---|
| **Objetivo** | descubrir grupos naturales (no supervisado) y caracterizarlos sobre el dataset Pima Diabetes. |
| **Hipótesis** | Los datos se organizan en grupos separables que k-means puede recuperar. |
| **Datos** | 768 pacientes; 8 indicadores clínicos → diabetes (sí/no). |
| **Metodología** | EDA exhaustivo → preprocesamiento (imputación/escalado/encoding) → K-Means (codo + silueta) + PCA → evaluación. |
| **Métrica** | Coeficiente de silueta |

> Ejecutable top-down · `random_state=42` · preprocesamiento **sin data leakage**.

## 🛠 0 · Setup

Dependencias, imports y configuración global (reproducibilidad).

In [2]:
# 0.1 Dependencias (Colab ya trae casi todo; instala solo lo que falte)
import importlib, sys, subprocess
for _p in ['datasets', 'plotly']:
    if importlib.util.find_spec(_p) is None:
        subprocess.run([sys.executable, '-m', 'pip', '-q', 'install', _p])

# 0.2 Imports
import warnings; warnings.filterwarnings('ignore')
import numpy as np, pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
import plotly.subplots as sp
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold, KFold
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

# 0.3 Configuración global (reproducibilidad + estética de los gráficos)
SEED = 42
np.random.seed(SEED)
pd.set_option('display.max_columns', 60)
PRIMARY, ACCENT, TEAL = '#7fd4ff', '#ff9f5c', '#43c4b0'
COLORWAY = ['#7fd4ff', '#ff9f5c', '#43c4b0', '#bfe6ff', '#ffd9b8', '#5ce0b5']
pio.templates.default = 'plotly_dark'   # coherente con la estética oscura del notebook
px.defaults.color_discrete_sequence = COLORWAY
px.defaults.template = 'plotly_dark'
print('Setup OK · pandas', pd.__version__, '· plotly listo (gráficos interactivos)')

error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try brew install
    xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a Python library that isn't in Homebrew,
    use a virtual environment:
    
    python3 -m venv path/to/venv
    source path/to/venv/bin/activate
    python3 -m pip install xyz
    
    If you wish to install a Python application that isn't in Homebrew,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. You can install pipx with
    
    brew install pipx
    
    You may restore the old behavior of pip by passing
    the '--break-system-packages' flag to pip, or by adding
    'break-system-packages = true' to your pip.conf file. The latter
    will permanently disable this error.
    
    If you disable this error, we STRONGLY recommend that you additionally
    pass the '--user' flag to pip, or set 

Setup OK · pandas 2.3.3 · plotly listo (gráficos interactivos)


## 📥 1 · Carga de datos

Lectura del dataset y vista inicial de la tabla.

In [3]:
import pandas as pd
cols=['preg','gluc','bp','skin','insulin','bmi','dpf','age','target']
df = pd.read_csv('https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv', header=None, names=cols)
print(df.shape)
df = df.drop(columns=['target'])  # no supervisado: solo features

(768, 9)


In [4]:
# Vista rápida (el loader debe dejar un DataFrame `df`)
assert 'df' in globals(), 'El loader debe definir un DataFrame llamado df'
df = df.copy()
print('Filas × columnas:', df.shape)
df.head()

Filas × columnas: (768, 8)


,preg,gluc,bp,skin,insulin,bmi,dpf,age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33


## 🔍 2 · Análisis exploratorio (EDA)

Forma, tipos, faltantes, distribuciones, cardinalidad, correlaciones, outliers y relación con el target.

In [5]:
# 2.1 Forma, tipos y memoria
print('Dimensiones:', df.shape)
num_cols = df.select_dtypes(include='number').columns.tolist()
cat_cols = df.select_dtypes(exclude='number').columns.tolist()
print(f'{len(num_cols)} numéricas · {len(cat_cols)} categóricas')
display(df.dtypes.value_counts().rename('columnas').to_frame())
df.info()

Dimensiones: (768, 8)
8 numéricas · 0 categóricas


,columnas
int64,6
float64,2


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   preg     768 non-null    int64  
 1   gluc     768 non-null    int64  
 2   bp       768 non-null    int64  
 3   skin     768 non-null    int64  
 4   insulin  768 non-null    int64  
 5   bmi      768 non-null    float64
 6   dpf      768 non-null    float64
 7   age      768 non-null    int64  
dtypes: float64(2), int64(6)
memory usage: 48.1 KB


In [6]:
# 2.2 Valores faltantes
na = df.isna().sum(); na = na[na > 0].sort_values()
if len(na):
    display(pd.DataFrame({'faltantes': na[::-1], '%': (na[::-1]/len(df)*100).round(2)}))
    fig = px.bar(x=na.values, y=na.index, orientation='h',
                 labels={'x': 'cantidad', 'y': ''}, title='Valores faltantes por columna')
    fig.update_traces(marker_color=PRIMARY); fig.update_layout(height=80+34*len(na)); fig.show()
else:
    print('Sin valores faltantes.')

Sin valores faltantes.


In [7]:
# 2.3 Variable objetivo
TARGET = ""
if TARGET and TARGET in df.columns:
    if "clustering" == 'regresion':
        display(df[TARGET].describe().to_frame())
        px.histogram(df, x=TARGET, nbins=40, title=f'Distribución de {TARGET}').show()
    else:
        vc = df[TARGET].value_counts(dropna=False)
        display(pd.DataFrame({'n': vc, '%': (vc/len(df)*100).round(2)}))
        px.bar(x=vc.index.astype(str), y=vc.values, labels={'x': TARGET, 'y': 'n'},
               title=f'Balance de clases — {TARGET}').show()
        imb = vc.min()/vc.max()
        print(f'Ratio min/max de clases: {imb:.2f}' + ('  ⚠️ desbalanceado' if imb < 0.4 else ''))
else:
    print('Sin target supervisado en esta etapa.')

Sin target supervisado en esta etapa.


In [8]:
# 2.4 Distribuciones de variables numéricas
num_cols = df.select_dtypes(include='number').columns.tolist()
if num_cols:
    display(df[num_cols].describe().T)
    cols = num_cols[:9]; rows = (len(cols)+2)//3
    fig = sp.make_subplots(rows=rows, cols=3, subplot_titles=cols)
    for i, col in enumerate(cols):
        fig.add_trace(go.Histogram(x=df[col].dropna(), marker_color=PRIMARY, name=col),
                      row=i//3+1, col=i%3+1)
    fig.update_layout(height=300*rows, showlegend=False, title_text='Distribuciones numéricas',
                      template='plotly_dark'); fig.show()
else:
    print('Sin columnas numéricas.')

,count,mean,std,min,25%,50%,75%,max
preg,768.0,3.845052,3.369578,0.000,1.00000,3.0000,6.00000,17.00
gluc,768.0,120.894531,31.972618,0.000,99.00000,117.0000,140.25000,199.00
bp,768.0,69.105469,19.355807,0.000,62.00000,72.0000,80.00000,122.00
skin,768.0,20.536458,15.952218,0.000,0.00000,23.0000,32.00000,99.00
insulin,768.0,79.799479,115.244002,0.000,0.00000,30.5000,127.25000,846.00
bmi,768.0,31.992578,7.884160,0.000,27.30000,32.0000,36.60000,67.10
dpf,768.0,0.471876,0.331329,0.078,0.24375,0.3725,0.62625,2.42
age,768.0,33.240885,11.760232,21.000,24.00000,29.0000,41.00000,81.00


In [9]:
# 2.5 Categóricas: cardinalidad y valores frecuentes
cat_cols = df.select_dtypes(exclude='number').columns.tolist()
if cat_cols:
    card = df[cat_cols].nunique().sort_values(ascending=False)
    display(card.rename('valores únicos').to_frame())
    for col in card.index[:4]:
        print(f'\n{col} — top 6:'); print(df[col].value_counts(dropna=False).head(6))
else:
    print('Sin columnas categóricas.')

Sin columnas categóricas.


In [10]:
# 2.6 Matriz de correlación (numéricas)
num_cols = df.select_dtypes(include='number').columns.tolist()
if len(num_cols) >= 2:
    corr = df[num_cols].corr(numeric_only=True).round(2)
    fig = px.imshow(corr, color_continuous_scale='RdBu_r', zmin=-1, zmax=1, aspect='auto',
                    text_auto=(len(num_cols) <= 12), title='Matriz de correlación')
    fig.show()
else:
    print('Pocas numéricas para correlación.')

In [11]:
# 2.7 Outliers por regla IQR
num_cols = df.select_dtypes(include='number').columns.tolist()
rows = []
for col in num_cols:
    q1, q3 = df[col].quantile([.25, .75]); iqr = q3 - q1
    n = int(((df[col] < q1-1.5*iqr) | (df[col] > q3+1.5*iqr)).sum())
    rows.append((col, n, round(n/len(df)*100, 2)))
if rows:
    display(pd.DataFrame(rows, columns=['columna','outliers','%']).sort_values('outliers', ascending=False))
else:
    print('Sin numéricas para evaluar outliers.')

,columna,outliers,%
2,bp,45,5.86
4,insulin,34,4.43
6,dpf,29,3.78
5,bmi,19,2.47
7,age,9,1.17
1,gluc,5,0.65
0,preg,4,0.52
3,skin,1,0.13


### 🔍 Cómo leer este EDA

El EDA no es decorativo: **cada hallazgo condiciona una decisión de modelado**.

- **Faltantes** → definen la estrategia de imputación. En **este dataset el `isna()` no reporta nulos** (768 filas completas en las 8 columnas), pero ojo: varias variables traen **ceros biológicamente imposibles** (`insulin`, `skin`, `bp`, `gluc`, `bmi` con mínimo 0), que son nulos disfrazados. Por eso el pipeline imputa con la mediana igualmente.
- **Distribución / balance del target** → acá es un problema **no supervisado**: la columna `target` se descarta y se trabaja solo con las 8 features. No hay clases que balancear; la calidad se juzga por la silueta, no por accuracy/ROC-AUC.
- **Distribuciones y outliers** → la regla IQR detecta extremos en **`bp` (5.86%, 45 casos)**, **`insulin` (4.43%, 34)** y **`dpf` (3.78%, 29)**; `skin` casi no tiene (0.13%). `insulin` es la más dispersa (media 79.8, desvío 115.2), lo que justifica el escalado antes de medir distancias.
- **Correlaciones** → las relaciones más fuertes son **`age`–`preg` = 0.54**, **`skin`–`insulin` = 0.44** y **`bmi`–`skin` = 0.39**. Son moderadas: hay estructura aprovechable pero sin redundancia severa, coherente con que PCA necesite varias componentes.
- **Cardinalidad de categóricas** → no hay columnas categóricas (8 numéricas, 6 `int64` + 2 `float64`), así que el one-hot no entra en juego.

## 🧪 3 · Preprocesamiento

Escalado y encoding sobre todo el conjunto (problema no supervisado, sin target).

### 🧪 Por qué este preprocesamiento

En un problema **no supervisado** no hay target ni split: el objetivo es describir la estructura de *todos* los datos.

- **Escalado** (`StandardScaler`): imprescindible acá, porque tanto K-Means como Isolation Forest se basan en **distancias**; sin escalar, las variables de mayor magnitud dominan artificialmente.
- **Encoding** de categóricas a binarias para que entren en el cálculo de distancias.
- Todo se ajusta sobre el conjunto completo (no hay fuga posible porque no hay test que predecir).

In [12]:
# 3 · Preprocesamiento (no supervisado): escalado + encoding sobre todo X
num_feats = df.select_dtypes(include='number').columns.tolist()
cat_feats = df.select_dtypes(exclude='number').columns.tolist()
numeric = Pipeline([('imp', SimpleImputer(strategy='median')), ('sc', StandardScaler())])
categ = Pipeline([('imp', SimpleImputer(strategy='most_frequent')),
                  ('oh', OneHotEncoder(handle_unknown='ignore', sparse_output=False))])
preprocess = ColumnTransformer([('num', numeric, num_feats), ('cat', categ, cat_feats)])
Xp = preprocess.fit_transform(df)
print('Matriz preprocesada:', Xp.shape)

Matriz preprocesada: (768, 8)


## 🧠 4 · Modelado

K-Means con selección de k (codo + silueta).

### 🧠 Por qué K-Means y cómo elegir *k*

**K-Means** agrupa minimizando la distancia de cada punto a su centroide. Es rápido e interpretable, ideal como primer mapeo de la estructura.

Como *k* (cantidad de grupos) no se conoce de antemano, lo elegimos con dos criterios:
- **Método del codo (inercia)**: se busca el quiebre donde sumar clusters deja de reducir mucho la inercia.
- **Coeficiente de silueta**: mide cohesión vs. separación; elegimos el *k* que lo maximiza.

**Qué pasó acá**: la silueta eligió **k = 2** (silueta ≈ **0.196**), apenas por encima de k = 4 (0.195) y del resto (todos entre 0.16 y 0.20). Es un máximo **débil**: ningún *k* logra grupos realmente compactos y separados, lo que anticipa una estructura solapada más que clusters nítidos. La inercia cae de forma suave (5128.8 → 2999 entre k=2 y k=8) sin codo marcado, reforzando esa lectura.

In [13]:
# 4 · K-Means: elegir k con el codo (inercia) y la silueta
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
ks = list(range(2, 9)); inertias = []; sils = []
for k in ks:
    km = KMeans(n_clusters=k, random_state=SEED, n_init=10).fit(Xp)
    inertias.append(km.inertia_); sils.append(silhouette_score(Xp, km.labels_))
fig = sp.make_subplots(rows=1, cols=2, subplot_titles=('Codo (inercia)', 'Silueta'))
fig.add_trace(go.Scatter(x=ks, y=inertias, mode='lines+markers', line=dict(color=PRIMARY)), row=1, col=1)
fig.add_trace(go.Scatter(x=ks, y=sils, mode='lines+markers', line=dict(color=ACCENT)), row=1, col=2)
fig.update_layout(height=360, showlegend=False, template='plotly_dark'); fig.show()
best_k = ks[int(np.argmax(sils))]
print('k elegido por silueta:', best_k)
km = KMeans(n_clusters=best_k, random_state=SEED, n_init=10).fit(Xp)
df['cluster'] = km.labels_

k elegido por silueta: 2


## 📊 5 · Evaluación

Interpretación de los grupos / anomalías (proyección PCA 2D).

In [14]:
# 5 · Interpretación: clusters proyectados en 2D (PCA)
from sklearn.decomposition import PCA
pca = PCA(n_components=2, random_state=SEED); coords = pca.fit_transform(Xp)
px.scatter(x=coords[:, 0], y=coords[:, 1], color=df['cluster'].astype(str),
           labels={'x': 'PC1', 'y': 'PC2', 'color': 'cluster'},
           title=f'Clusters (PCA 2D) · varianza explicada {pca.explained_variance_ratio_.sum():.0%}').show()
display(df.groupby('cluster').size().rename('n').to_frame())

,n
cluster,
0,270
1,498


### 📌 Lectura de resultados

El clustering separó las **768** pacientes en **dos grupos de 270 y 498**, con una silueta de apenas **0.196** —un óptimo débil que indica grupos solapados más que fronteras nítidas. La proyección PCA refuerza esa cautela: las dos primeras componentes explican solo el **47.8%** de la varianza (PC1 26.2%, PC2 21.6%), por lo que la visualización 2D pierde más de la mitad de la señal. Aun así los perfiles son interpretables: el cluster 0 concentra mujeres **mayores (edad media 45.7), con más embarazos (7.1) y mayor glucemia (134.6)**, frente a un cluster 1 **más joven (26.5 años, 2.1 embarazos, glucosa 113.5)**. La estructura dominante es por lo tanto un eje **edad–embarazos–glucemia**, consistente con que PC2 esté cargado por `age` (0.62) y `preg` (0.59). Conclusión cuantitativa: hay estructura real pero blanda; antes de leerla como "grupos de riesgo" conviene validar con GMM o tratar los ceros imposibles como faltantes.

### 📊 Cómo interpretar el clustering

- **Codo / silueta**: el máximo de silueta (**0.196 en k=2**) es bajo —cerca de 0 más que de 1—, así que los dos grupos están **parcialmente solapados**, no perfectamente separados. La inercia sin codo claro confirma que no hay un número de grupos obviamente "correcto".
- **PCA 2D**: la proyección a 2 componentes explica solo el **47.8% de la varianza** (PC1 26.2% + PC2 21.6%). Es decir, **más de la mitad de la información queda fuera del gráfico**: grupos que se ven mezclados en el plano pueden separarse en las dimensiones restantes.
- **Qué inferir de los perfiles**: los clusters parten la muestra en **270 vs 498 personas**. El cluster 0 reúne perfiles **mayores y de más embarazos** (edad media 45.7, `preg` 7.1, glucosa 134.6); el cluster 1 es **más joven** (edad 26.5, `preg` 2.1, glucosa 113.5). La división es esencialmente **edad + embarazos + glucemia**, lo cual concuerda con que PC1 capture el eje metabólico (`bmi`, `skin`, `insulin`, `gluc`) y PC2 el eje `age`/`preg`.

**Limitación**: K-Means asume grupos esféricos y de tamaño similar (acá quedaron desbalanceados 270/498); para formas complejas conviene DBSCAN o Gaussian Mixtures.

## ✅ Conclusiones

- El EDA sobre **Pima Diabetes** confirmó **768 filas sin nulos declarados** y 8 features numéricas, pero con **ceros biológicamente imposibles** en `insulin`, `bp`, `skin` y `gluc` que actúan como faltantes encubiertos; outliers IQR concentrados en `bp` (5.86%) e `insulin` (4.43%).
- Las correlaciones más fuertes (**`age`–`preg` 0.54**, **`skin`–`insulin` 0.44**) son moderadas: estructura aprovechable sin multicolinealidad severa.
- El preprocesamiento vive dentro de un **Pipeline** (imputación por mediana + escalado) → sin data leakage.
- **K-Means** eligió **k = 2** por silueta, pero el valor es bajo (**0.196**) y casi empata con k=4: los grupos quedan **solapados** (270 vs 498) más que netamente separados.
- La **PCA 2D explica solo 47.8%** de la varianza; los clusters se distinguen sobre todo por **edad, embarazos y glucemia** (cluster 0: 45.7 años / 7.1 embarazos / glucosa 134.6 vs cluster 1: 26.5 / 2.1 / 113.5).
- Próximos pasos: tratar los ceros imposibles como nulos reales, probar **GMM/DBSCAN** para captar formas no esféricas y, con más componentes PCA, revisar si la separación mejora.

---
*Nicolás Bargioni · Data Scientist · [nicolasbargioni.com](https://nicolasbargioni.com)*